                                                                                                                                                                                                   pg_get_functiondef                                                                                                                                                                                                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_generate_sponsorship_invite(p_event_id uuid, p_prospect_name character varying, p_prospect_email character varying DEFAULT NULL::character varying, p_prospect_company character varying DEFAULT NULL::character varying, p_discount_percent numeric DEFAULT 0, p_valid_until timestamp with time zone DEFAULT NULL::timestamp with time zone, p_notes text DEFAULT NULL::text)+
  RETURNS TABLE(invite_id uuid, hash character varying, full_url text)                                                                                                                                                                                                                                                                                                                                                  +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                      +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                      +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                          +
 DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                +
   v_invite_id UUID;                                                                                                                                                                                                                                                                                                                                                                                                    +
   v_hash VARCHAR;                                                                                                                                                                                                                                                                                                                                                                                                      +
   v_creator_email TEXT;                                                                                                                                                                                                                                                                                                                                                                                                +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                  +
   -- Get creator email from JWT                                                                                                                                                                                                                                                                                                                                                                                        +
   v_creator_email := current_setting('request.jwt.claims', true)::json->>'email';                                                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                                                                                                                        +
   -- Generate unique hash                                                                                                                                                                                                                                                                                                                                                                                              +
   LOOP                                                                                                                                                                                                                                                                                                                                                                                                                 +
     v_hash := generate_sponsorship_invite_hash();                                                                                                                                                                                                                                                                                                                                                                      +
     EXIT WHEN NOT EXISTS (SELECT 1 FROM sponsorship_invites si WHERE si.hash = v_hash);                                                                                                                                                                                                                                                                                                                                +
   END LOOP;                                                                                                                                                                                                                                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                                                                                                                                                                        +
   -- Create invite                                                                                                                                                                                                                                                                                                                                                                                                     +
   INSERT INTO sponsorship_invites (                                                                                                                                                                                                                                                                                                                                                                                    +
     event_id,                                                                                                                                                                                                                                                                                                                                                                                                          +
     hash,                                                                                                                                                                                                                                                                                                                                                                                                              +
     prospect_name,                                                                                                                                                                                                                                                                                                                                                                                                     +
     prospect_email,                                                                                                                                                                                                                                                                                                                                                                                                    +
     prospect_company,                                                                                                                                                                                                                                                                                                                                                                                                  +
     discount_percent,                                                                                                                                                                                                                                                                                                                                                                                                  +
     valid_until,                                                                                                                                                                                                                                                                                                                                                                                                       +
     notes,                                                                                                                                                                                                                                                                                                                                                                                                             +
     created_by                                                                                                                                                                                                                                                                                                                                                                                                         +
   ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                           +
     p_event_id,                                                                                                                                                                                                                                                                                                                                                                                                        +
     v_hash,                                                                                                                                                                                                                                                                                                                                                                                                            +
     p_prospect_name,                                                                                                                                                                                                                                                                                                                                                                                                   +
     p_prospect_email,                                                                                                                                                                                                                                                                                                                                                                                                  +
     p_prospect_company,                                                                                                                                                                                                                                                                                                                                                                                                +
     p_discount_percent,                                                                                                                                                                                                                                                                                                                                                                                                +
     p_valid_until,                                                                                                                                                                                                                                                                                                                                                                                                     +
     p_notes,                                                                                                                                                                                                                                                                                                                                                                                                           +
     v_creator_email                                                                                                                                                                                                                                                                                                                                                                                                    +
   )                                                                                                                                                                                                                                                                                                                                                                                                                    +
   RETURNING id INTO v_invite_id;                                                                                                                                                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                                                                                                                                                                                        +
   RETURN QUERY SELECT                                                                                                                                                                                                                                                                                                                                                                                                  +
     v_invite_id,                                                                                                                                                                                                                                                                                                                                                                                                       +
     v_hash,                                                                                                                                                                                                                                                                                                                                                                                                            +
     'https://artb.art/sponsor/' || v_hash AS full_url;                                                                                                                                                                                                                                                                                                                                                                 +
 END;                                                                                                                                                                                                                                                                                                                                                                                                                   +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                             +
 
(1 row)

