                                                                                                                                           pg_get_functiondef                                                                                                                                           
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_insert_artist_profile(p_name character varying, p_phone character varying, p_email character varying DEFAULT NULL::character varying, p_city character varying DEFAULT NULL::character varying, p_instagram character varying DEFAULT NULL::character varying)+
  RETURNS uuid                                                                                                                                                                                                                                                                                         +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                     +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                     +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                          +
 AS $function$                                                                                                                                                                                                                                                                                         +
 DECLARE                                                                                                                                                                                                                                                                                               +
   new_artist_id UUID;                                                                                                                                                                                                                                                                                 +
   current_phone TEXT;                                                                                                                                                                                                                                                                                 +
 BEGIN                                                                                                                                                                                                                                                                                                 +
   -- Get current user's phone from JWT                                                                                                                                                                                                                                                                +
   current_phone := auth.jwt() ->> 'phone';                                                                                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                                                       +
   -- Check if user is an admin - simplified check                                                                                                                                                                                                                                                     +
   IF NOT EXISTS (                                                                                                                                                                                                                                                                                     +
     SELECT 1 FROM event_admins                                                                                                                                                                                                                                                                        +
     WHERE phone = current_phone                                                                                                                                                                                                                                                                       +
     AND admin_level IN ('super', 'admin')                                                                                                                                                                                                                                                             +
   ) THEN                                                                                                                                                                                                                                                                                              +
     RAISE EXCEPTION 'Unauthorized: Admin access required. Phone: %', current_phone;                                                                                                                                                                                                                   +
   END IF;                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                       +
   -- Insert the artist profile                                                                                                                                                                                                                                                                        +
   INSERT INTO artist_profiles (name, phone, email, city, instagram)                                                                                                                                                                                                                                   +
   VALUES (p_name, p_phone, p_email, p_city, p_instagram)                                                                                                                                                                                                                                              +
   RETURNING id INTO new_artist_id;                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                       +
   RETURN new_artist_id;                                                                                                                                                                                                                                                                               +
 END;                                                                                                                                                                                                                                                                                                  +
 $function$                                                                                                                                                                                                                                                                                            +
 
(1 row)

