                                                                                                                                                                                                                                               pg_get_functiondef                                                                                                                                                                                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_store_artwork_ai_analysis(p_artist_profile_id uuid, p_artwork_type text, p_source_id uuid, p_cloudflare_id text, p_image_url text, p_technique_analysis text, p_style_assessment text, p_materials_description text, p_market_value_analysis text, p_live_performance_potential text, p_openai_model text DEFAULT 'gpt-4o-mini'::text, p_prompt_used text DEFAULT ''::text, p_token_usage jsonb DEFAULT '{}'::jsonb, p_api_response_metadata jsonb DEFAULT '{}'::jsonb)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
  DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       +
      new_id UUID;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
      -- Insert new analysis                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
      INSERT INTO art_media_ai_caption (                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
          artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
          artwork_type,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
          source_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
          cloudflare_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
          image_url,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
          technique_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
          style_assessment,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     +
          materials_description,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
          market_value_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
          live_performance_potential,                                                                                                                                                                                                                                                                                                                                                                                                                                                                           +
          openai_model,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
          prompt_used,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
          token_usage,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
          api_response_metadata                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
      ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
          p_artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
          p_artwork_type,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       +
          p_source_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
          p_cloudflare_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
          p_image_url,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
          p_technique_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
          p_style_assessment,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
          p_materials_description,                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
          p_market_value_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
          p_live_performance_potential,                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
          p_openai_model,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       +
          p_prompt_used,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
          p_token_usage,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
          p_api_response_metadata                                                                                                                                                                                                                                                                                                                                                                                                                                                                               +
      )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
      ON CONFLICT (artist_profile_id, image_url, artwork_type)                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
      DO UPDATE SET                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             +
          technique_analysis = EXCLUDED.technique_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                                     +
          style_assessment = EXCLUDED.style_assessment,                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
          materials_description = EXCLUDED.materials_description,                                                                                                                                                                                                                                                                                                                                                                                                                                               +
          market_value_analysis = EXCLUDED.market_value_analysis,                                                                                                                                                                                                                                                                                                                                                                                                                                               +
          live_performance_potential = EXCLUDED.live_performance_potential,                                                                                                                                                                                                                                                                                                                                                                                                                                     +
          openai_model = EXCLUDED.openai_model,                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
          prompt_used = EXCLUDED.prompt_used,                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
          token_usage = EXCLUDED.token_usage,                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
          api_response_metadata = EXCLUDED.api_response_metadata,                                                                                                                                                                                                                                                                                                                                                                                                                                               +
          generated_at = NOW(),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
          expires_at = NOW() + INTERVAL '5 years'                                                                                                                                                                                                                                                                                                                                                                                                                                                               +
      RETURNING id INTO new_id;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
      RETURN new_id;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
  END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
  $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
 
(1 row)

