                                                                                                                                                            pg_get_functiondef                                                                                                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_get_bulk_artist_data(p_limit integer DEFAULT 100, p_offset integer DEFAULT 0, p_search_term text DEFAULT NULL::text)                                                                                                                                                                             +
  RETURNS TABLE(artist_profile_id uuid, artist_name text, artist_number text, event_eid text, event_name text, city_name text, event_date text, bio_preview text, full_bio text, promotion_artwork_url text, has_bio boolean, has_promo_image boolean, confirmation_date timestamp with time zone, created_at timestamp without time zone)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                        +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                        +
 AS $function$                                                                                                                                                                                                                                                                                                                            +
 BEGIN                                                                                                                                                                                                                                                                                                                                    +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                           +
   SELECT                                                                                                                                                                                                                                                                                                                                 +
     ap.id as artist_profile_id,                                                                                                                                                                                                                                                                                                          +
     COALESCE(TRIM(ap.name), 'Unknown Artist') as artist_name,                                                                                                                                                                                                                                                                            +
     COALESCE(ap.entry_id::TEXT, 'N/A') as artist_number,                                                                                                                                                                                                                                                                                 +
     ac.event_eid,                                                                                                                                                                                                                                                                                                                        +
     COALESCE(TRIM(e.name), ac.event_eid) as event_name,                                                                                                                                                                                                                                                                                  +
     COALESCE(TRIM(c.name), 'Unknown City') as city_name,                                                                                                                                                                                                                                                                                 +
     CASE                                                                                                                                                                                                                                                                                                                                 +
       WHEN e.event_start_datetime IS NOT NULL                                                                                                                                                                                                                                                                                            +
       THEN TO_CHAR(e.event_start_datetime, 'Mon DD, YYYY')                                                                                                                                                                                                                                                                               +
       ELSE 'TBD'                                                                                                                                                                                                                                                                                                                         +
     END as event_date,                                                                                                                                                                                                                                                                                                                   +
     LEFT(COALESCE(TRIM(ap.abhq_bio), ''), 100) as bio_preview,                                                                                                                                                                                                                                                                           +
     COALESCE(TRIM(ap.abhq_bio), '') as full_bio,                                                                                                                                                                                                                                                                                         +
     COALESCE(TRIM(ac.promotion_artwork_url), '') as promotion_artwork_url,                                                                                                                                                                                                                                                               +
     (ap.abhq_bio IS NOT NULL AND TRIM(ap.abhq_bio) != '') as has_bio,                                                                                                                                                                                                                                                                    +
     (ac.promotion_artwork_url IS NOT NULL AND TRIM(ac.promotion_artwork_url) != '') as has_promo_image,                                                                                                                                                                                                                                  +
     ac.confirmation_date,                                                                                                                                                                                                                                                                                                                +
     ac.created_at                                                                                                                                                                                                                                                                                                                        +
   FROM artist_confirmations ac                                                                                                                                                                                                                                                                                                           +
   JOIN artist_profiles ap ON ac.artist_profile_id = ap.id                                                                                                                                                                                                                                                                                +
   LEFT JOIN events e ON ac.event_eid = e.eid                                                                                                                                                                                                                                                                                             +
   LEFT JOIN cities c ON e.city_id = c.id                                                                                                                                                                                                                                                                                                 +
   WHERE                                                                                                                                                                                                                                                                                                                                  +
     ac.confirmation_status = 'confirmed'                                                                                                                                                                                                                                                                                                 +
     AND ac.withdrawn_at IS NULL                                                                                                                                                                                                                                                                                                          +
     -- Only show events from 5 days ago to future                                                                                                                                                                                                                                                                                        +
     AND (e.event_start_datetime IS NULL OR e.event_start_datetime >= (NOW() - INTERVAL '5 days'))                                                                                                                                                                                                                                        +
     AND (                                                                                                                                                                                                                                                                                                                                +
       p_search_term IS NULL                                                                                                                                                                                                                                                                                                              +
       OR LOWER(ap.name) LIKE '%' || LOWER(p_search_term) || '%'                                                                                                                                                                                                                                                                          +
       OR LOWER(ac.event_eid) LIKE '%' || LOWER(p_search_term) || '%'                                                                                                                                                                                                                                                                     +
       OR ap.entry_id::TEXT LIKE '%' || p_search_term || '%'                                                                                                                                                                                                                                                                              +
     )                                                                                                                                                                                                                                                                                                                                    +
   ORDER BY                                                                                                                                                                                                                                                                                                                               +
     -- Sort by event date ascending (future events first, then recent past)                                                                                                                                                                                                                                                              +
     COALESCE(e.event_start_datetime, '2099-12-31'::TIMESTAMP) ASC,                                                                                                                                                                                                                                                                       +
     -- Then prioritize artists missing bio/image                                                                                                                                                                                                                                                                                         +
     CASE WHEN ap.abhq_bio IS NULL OR TRIM(ap.abhq_bio) = '' THEN 0 ELSE 1 END,                                                                                                                                                                                                                                                           +
     CASE WHEN ac.promotion_artwork_url IS NULL OR TRIM(ac.promotion_artwork_url) = '' THEN 0 ELSE 1 END,                                                                                                                                                                                                                                 +
     ap.name ASC                                                                                                                                                                                                                                                                                                                          +
   LIMIT p_limit                                                                                                                                                                                                                                                                                                                          +
   OFFSET p_offset;                                                                                                                                                                                                                                                                                                                       +
 END;                                                                                                                                                                                                                                                                                                                                     +
 $function$                                                                                                                                                                                                                                                                                                                               +
 
(1 row)

