                                                                                                                                                                                                       pg_get_functiondef                                                                                                                                                                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_store_artist_ai_intel(p_artist_profile_id uuid, p_ai_summary jsonb, p_participation_insights jsonb DEFAULT NULL::jsonb, p_bio_analysis jsonb DEFAULT NULL::jsonb, p_recommendations jsonb DEFAULT NULL::jsonb, p_strengths text[] DEFAULT NULL::text[], p_growth_areas text[] DEFAULT NULL::text[], p_openai_model text DEFAULT 'gpt-4'::text, p_token_usage jsonb DEFAULT NULL::jsonb)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                                                                                                  +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                              +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                              +
  SET search_path TO 'pg_catalog', 'public', 'auth', 'extensions'                                                                                                                                                                                                                                                                                                                                                               +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                  +
  DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                       +
    v_intel_id UUID;                                                                                                                                                                                                                                                                                                                                                                                                            +
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                         +
    -- Delete any existing record for this artist (upsert pattern)                                                                                                                                                                                                                                                                                                                                                              +
    DELETE FROM artist_ai_intel WHERE artist_profile_id = p_artist_profile_id;                                                                                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                                                                                                                                                +
    -- Insert new AI intel record                                                                                                                                                                                                                                                                                                                                                                                               +
    INSERT INTO artist_ai_intel (                                                                                                                                                                                                                                                                                                                                                                                               +
      artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                        +
      ai_summary,                                                                                                                                                                                                                                                                                                                                                                                                               +
      participation_insights,                                                                                                                                                                                                                                                                                                                                                                                                   +
      bio_analysis,                                                                                                                                                                                                                                                                                                                                                                                                             +
      recommendations,                                                                                                                                                                                                                                                                                                                                                                                                          +
      strengths,                                                                                                                                                                                                                                                                                                                                                                                                                +
      growth_areas,                                                                                                                                                                                                                                                                                                                                                                                                             +
      openai_model,                                                                                                                                                                                                                                                                                                                                                                                                             +
      token_usage                                                                                                                                                                                                                                                                                                                                                                                                               +
    ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                                  +
      p_artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                      +
      p_ai_summary,                                                                                                                                                                                                                                                                                                                                                                                                             +
      p_participation_insights,                                                                                                                                                                                                                                                                                                                                                                                                 +
      p_bio_analysis,                                                                                                                                                                                                                                                                                                                                                                                                           +
      p_recommendations,                                                                                                                                                                                                                                                                                                                                                                                                        +
      p_strengths,                                                                                                                                                                                                                                                                                                                                                                                                              +
      p_growth_areas,                                                                                                                                                                                                                                                                                                                                                                                                           +
      p_openai_model,                                                                                                                                                                                                                                                                                                                                                                                                           +
      p_token_usage                                                                                                                                                                                                                                                                                                                                                                                                             +
    ) RETURNING id INTO v_intel_id;                                                                                                                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                                                                                                                                                +
    RETURN v_intel_id;                                                                                                                                                                                                                                                                                                                                                                                                          +
  END;                                                                                                                                                                                                                                                                                                                                                                                                                          +
  $function$                                                                                                                                                                                                                                                                                                                                                                                                                    +
 
(1 row)

