                                                                                                                                             pg_get_functiondef                                                                                                                                              
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_insert_artist_profile_temp(p_name character varying, p_phone character varying, p_email character varying DEFAULT NULL::character varying, p_city character varying DEFAULT NULL::character varying, p_instagram character varying DEFAULT NULL::character varying)+
  RETURNS uuid                                                                                                                                                                                                                                                                                              +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                          +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                          +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                               +
 AS $function$                                                                                                                                                                                                                                                                                              +
 DECLARE                                                                                                                                                                                                                                                                                                    +
   new_artist_id UUID;                                                                                                                                                                                                                                                                                      +
   clean_phone VARCHAR;                                                                                                                                                                                                                                                                                     +
   digits_only VARCHAR;                                                                                                                                                                                                                                                                                     +
 BEGIN                                                                                                                                                                                                                                                                                                      +
   -- Convert phone to E.164 format                                                                                                                                                                                                                                                                         +
   -- Remove all non-digit characters                                                                                                                                                                                                                                                                       +
   digits_only := regexp_replace(p_phone, '[^0-9]', '', 'g');                                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                                                                                            +
   -- Convert to E.164 based on common patterns                                                                                                                                                                                                                                                             +
   IF digits_only ~ '^1[0-9]{10}$' THEN                                                                                                                                                                                                                                                                     +
     -- North American: 1XXXXXXXXXX -> +1XXXXXXXXXX                                                                                                                                                                                                                                                         +
     clean_phone := '+' || digits_only;                                                                                                                                                                                                                                                                     +
   ELSIF digits_only ~ '^[2-9][0-9]{9}$' THEN                                                                                                                                                                                                                                                               +
     -- North American without country code: XXXXXXXXXX -> +1XXXXXXXXXX                                                                                                                                                                                                                                     +
     clean_phone := '+1' || digits_only;                                                                                                                                                                                                                                                                    +
   ELSIF digits_only ~ '^44[0-9]{10}$' THEN                                                                                                                                                                                                                                                                 +
     -- UK: 44XXXXXXXXXX -> +44XXXXXXXXXX                                                                                                                                                                                                                                                                   +
     clean_phone := '+' || digits_only;                                                                                                                                                                                                                                                                     +
   ELSIF digits_only ~ '^61[0-9]{9}$' THEN                                                                                                                                                                                                                                                                  +
     -- Australia: 61XXXXXXXXX -> +61XXXXXXXXX                                                                                                                                                                                                                                                              +
     clean_phone := '+' || digits_only;                                                                                                                                                                                                                                                                     +
   ELSIF digits_only ~ '^64[0-9]{8,9}$' THEN                                                                                                                                                                                                                                                                +
     -- New Zealand: 64XXXXXXXX or 64XXXXXXXXX -> +64XXXXXXXX(X)                                                                                                                                                                                                                                            +
     clean_phone := '+' || digits_only;                                                                                                                                                                                                                                                                     +
   ELSIF length(digits_only) >= 10 THEN                                                                                                                                                                                                                                                                     +
     -- International format: assume already has country code                                                                                                                                                                                                                                               +
     clean_phone := '+' || digits_only;                                                                                                                                                                                                                                                                     +
   ELSE                                                                                                                                                                                                                                                                                                     +
     -- Invalid phone number                                                                                                                                                                                                                                                                                +
     RAISE EXCEPTION 'Invalid phone number format: %', p_phone;                                                                                                                                                                                                                                             +
   END IF;                                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                                            +
   -- Insert the artist profile with E.164 phone                                                                                                                                                                                                                                                            +
   INSERT INTO artist_profiles (name, phone, email, city, instagram)                                                                                                                                                                                                                                        +
   VALUES (p_name, clean_phone, p_email, p_city, p_instagram)                                                                                                                                                                                                                                               +
   RETURNING id INTO new_artist_id;                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                            +
   RETURN new_artist_id;                                                                                                                                                                                                                                                                                    +
 END;                                                                                                                                                                                                                                                                                                       +
 $function$                                                                                                                                                                                                                                                                                                 +
 
(1 row)

