                                                                                                                                                                              pg_get_functiondef                                                                                                                                                                              
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_get_artwork_ai_analysis(p_artist_profile_id uuid, p_image_url text, p_artwork_type text DEFAULT 'sample_work'::text)                                                                                                                                                                                                                +
  RETURNS TABLE(id uuid, artwork_type text, source_id uuid, cloudflare_id text, image_url text, technique_analysis text, style_assessment text, materials_description text, market_value_analysis text, live_performance_potential text, openai_model text, token_usage jsonb, generated_at timestamp with time zone, expires_at timestamp with time zone, is_cached boolean)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                                                                                                                                                               +
  BEGIN                                                                                                                                                                                                                                                                                                                                                                      +
      RETURN QUERY                                                                                                                                                                                                                                                                                                                                                           +
      SELECT                                                                                                                                                                                                                                                                                                                                                                 +
          amc.id,                                                                                                                                                                                                                                                                                                                                                            +
          amc.artwork_type,                                                                                                                                                                                                                                                                                                                                                  +
          amc.source_id,                                                                                                                                                                                                                                                                                                                                                     +
          amc.cloudflare_id,                                                                                                                                                                                                                                                                                                                                                 +
          amc.image_url,                                                                                                                                                                                                                                                                                                                                                     +
          amc.technique_analysis,                                                                                                                                                                                                                                                                                                                                            +
          amc.style_assessment,                                                                                                                                                                                                                                                                                                                                              +
          amc.materials_description,                                                                                                                                                                                                                                                                                                                                         +
          amc.market_value_analysis,                                                                                                                                                                                                                                                                                                                                         +
          amc.live_performance_potential,                                                                                                                                                                                                                                                                                                                                    +
          amc.openai_model,                                                                                                                                                                                                                                                                                                                                                  +
          amc.token_usage,                                                                                                                                                                                                                                                                                                                                                   +
          amc.generated_at,                                                                                                                                                                                                                                                                                                                                                  +
          amc.expires_at,                                                                                                                                                                                                                                                                                                                                                    +
          (amc.expires_at > NOW()) as is_cached                                                                                                                                                                                                                                                                                                                              +
      FROM art_media_ai_caption amc                                                                                                                                                                                                                                                                                                                                          +
      WHERE amc.artist_profile_id = p_artist_profile_id                                                                                                                                                                                                                                                                                                                      +
          AND amc.image_url = p_image_url                                                                                                                                                                                                                                                                                                                                    +
          AND amc.artwork_type = p_artwork_type                                                                                                                                                                                                                                                                                                                              +
          AND amc.expires_at > NOW()                                                                                                                                                                                                                                                                                                                                         +
      ORDER BY amc.generated_at DESC                                                                                                                                                                                                                                                                                                                                         +
      LIMIT 1;                                                                                                                                                                                                                                                                                                                                                               +
  END;                                                                                                                                                                                                                                                                                                                                                                       +
  $function$                                                                                                                                                                                                                                                                                                                                                                 +
 
(1 row)

