                                                                                                                    pg_get_functiondef                                                                                                                    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.admin_get_artist_ai_intel(p_artist_profile_id uuid)                                                                                                                                                                   +
  RETURNS TABLE(id uuid, ai_summary jsonb, participation_insights jsonb, bio_analysis jsonb, recommendations jsonb, strengths text[], growth_areas text[], generated_at timestamp with time zone, expires_at timestamp with time zone, is_cached boolean)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                       +
  SECURITY DEFINER                                                                                                                                                                                                                                       +
 AS $function$                                                                                                                                                                                                                                           +
 BEGIN                                                                                                                                                                                                                                                   +
   -- First, clean up expired records for this artist                                                                                                                                                                                                    +
   DELETE FROM artist_ai_intel                                                                                                                                                                                                                           +
   WHERE artist_profile_id = p_artist_profile_id                                                                                                                                                                                                         +
     AND expires_at < NOW();                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                         +
   -- Try to get valid cached AI intel                                                                                                                                                                                                                   +
   RETURN QUERY                                                                                                                                                                                                                                          +
   SELECT                                                                                                                                                                                                                                                +
     ai.id,                                                                                                                                                                                                                                              +
     ai.ai_summary,                                                                                                                                                                                                                                      +
     ai.participation_insights,                                                                                                                                                                                                                          +
     ai.bio_analysis,                                                                                                                                                                                                                                    +
     ai.recommendations,                                                                                                                                                                                                                                 +
     ai.strengths,                                                                                                                                                                                                                                       +
     ai.growth_areas,                                                                                                                                                                                                                                    +
     ai.generated_at,                                                                                                                                                                                                                                    +
     ai.expires_at,                                                                                                                                                                                                                                      +
     TRUE as is_cached                                                                                                                                                                                                                                   +
   FROM artist_ai_intel ai                                                                                                                                                                                                                               +
   WHERE ai.artist_profile_id = p_artist_profile_id                                                                                                                                                                                                      +
     AND ai.expires_at > NOW()                                                                                                                                                                                                                           +
   ORDER BY ai.generated_at DESC                                                                                                                                                                                                                         +
   LIMIT 1;                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                         +
   -- If no valid cache found, return empty result                                                                                                                                                                                                       +
   -- (The edge function will handle generation)                                                                                                                                                                                                         +
   IF NOT FOUND THEN                                                                                                                                                                                                                                     +
     RETURN QUERY                                                                                                                                                                                                                                        +
     SELECT                                                                                                                                                                                                                                              +
       NULL::UUID as id,                                                                                                                                                                                                                                 +
       NULL::JSONB as ai_summary,                                                                                                                                                                                                                        +
       NULL::JSONB as participation_insights,                                                                                                                                                                                                            +
       NULL::JSONB as bio_analysis,                                                                                                                                                                                                                      +
       NULL::JSONB as recommendations,                                                                                                                                                                                                                   +
       NULL::TEXT[] as strengths,                                                                                                                                                                                                                        +
       NULL::TEXT[] as growth_areas,                                                                                                                                                                                                                     +
       NULL::TIMESTAMPTZ as generated_at,                                                                                                                                                                                                                +
       NULL::TIMESTAMPTZ as expires_at,                                                                                                                                                                                                                  +
       FALSE as is_cached;                                                                                                                                                                                                                               +
   END IF;                                                                                                                                                                                                                                               +
 END;                                                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                                              +
 
(1 row)

