                                                                                                                                                                                                         pg_get_functiondef                                                                                                                                                                                                          
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.find_potential_event_progressions()                                                                                                                                                                                                                                                                                                                                                              +
  RETURNS TABLE(artist_name character varying, artist_number character varying, first_event_eid character varying, first_event_name character varying, first_event_date timestamp without time zone, first_event_city character varying, r3_votes bigint, next_event_eid character varying, next_event_name character varying, next_event_date timestamp without time zone, next_event_city character varying, days_between integer)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                      +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                              +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                     +
   WITH r3_winners AS (                                                                                                                                                                                                                                                                                                                                                                                                             +
     -- Find the artist with the most votes in Round 3 for each event                                                                                                                                                                                                                                                                                                                                                               +
     SELECT                                                                                                                                                                                                                                                                                                                                                                                                                         +
       v.event_id,                                                                                                                                                                                                                                                                                                                                                                                                                  +
       v.artist_id,                                                                                                                                                                                                                                                                                                                                                                                                                 +
       v.votes,                                                                                                                                                                                                                                                                                                                                                                                                                     +
       ROW_NUMBER() OVER (PARTITION BY v.event_id ORDER BY v.votes DESC) as rank                                                                                                                                                                                                                                                                                                                                                    +
     FROM votes v                                                                                                                                                                                                                                                                                                                                                                                                                   +
     WHERE v.round = 3                                                                                                                                                                                                                                                                                                                                                                                                              +
   ),                                                                                                                                                                                                                                                                                                                                                                                                                               +
   winner_events AS (                                                                                                                                                                                                                                                                                                                                                                                                               +
     -- Get full details for winning artists and their events                                                                                                                                                                                                                                                                                                                                                                       +
     SELECT                                                                                                                                                                                                                                                                                                                                                                                                                         +
       w.artist_id,                                                                                                                                                                                                                                                                                                                                                                                                                 +
       a.name as artist_name,                                                                                                                                                                                                                                                                                                                                                                                                       +
       a.artist_number,                                                                                                                                                                                                                                                                                                                                                                                                             +
       e.id as event_id,                                                                                                                                                                                                                                                                                                                                                                                                            +
       e.eid as event_eid,                                                                                                                                                                                                                                                                                                                                                                                                          +
       e.name as event_name,                                                                                                                                                                                                                                                                                                                                                                                                        +
       e.event_start_datetime,                                                                                                                                                                                                                                                                                                                                                                                                      +
       c.name as city_name,                                                                                                                                                                                                                                                                                                                                                                                                         +
       w.votes as r3_votes                                                                                                                                                                                                                                                                                                                                                                                                          +
     FROM r3_winners w                                                                                                                                                                                                                                                                                                                                                                                                              +
     JOIN artists a ON a.id = w.artist_id                                                                                                                                                                                                                                                                                                                                                                                           +
     JOIN events e ON e.id = w.event_id                                                                                                                                                                                                                                                                                                                                                                                             +
     JOIN cities c ON c.id = e.city_id                                                                                                                                                                                                                                                                                                                                                                                              +
     WHERE w.rank = 1  -- Only the winner (most votes in R3)                                                                                                                                                                                                                                                                                                                                                                        +
       AND e.event_start_datetime >= '2018-01-01'::timestamp                                                                                                                                                                                                                                                                                                                                                                        +
   ),                                                                                                                                                                                                                                                                                                                                                                                                                               +
   artist_next_events AS (                                                                                                                                                                                                                                                                                                                                                                                                          +
     -- Find subsequent events the winner competed in                                                                                                                                                                                                                                                                                                                                                                               +
     SELECT                                                                                                                                                                                                                                                                                                                                                                                                                         +
       we.artist_id,                                                                                                                                                                                                                                                                                                                                                                                                                +
       we.artist_name,                                                                                                                                                                                                                                                                                                                                                                                                              +
       we.artist_number,                                                                                                                                                                                                                                                                                                                                                                                                            +
       we.event_eid as first_event_eid,                                                                                                                                                                                                                                                                                                                                                                                             +
       we.event_name as first_event_name,                                                                                                                                                                                                                                                                                                                                                                                           +
       we.event_start_datetime as first_event_date,                                                                                                                                                                                                                                                                                                                                                                                 +
       we.city_name as first_event_city,                                                                                                                                                                                                                                                                                                                                                                                            +
       we.r3_votes,                                                                                                                                                                                                                                                                                                                                                                                                                 +
       e2.eid as next_event_eid,                                                                                                                                                                                                                                                                                                                                                                                                    +
       e2.name as next_event_name,                                                                                                                                                                                                                                                                                                                                                                                                  +
       e2.event_start_datetime as next_event_date,                                                                                                                                                                                                                                                                                                                                                                                  +
       c2.name as next_event_city,                                                                                                                                                                                                                                                                                                                                                                                                  +
       EXTRACT(DAY FROM (e2.event_start_datetime - we.event_start_datetime))::integer as days_between                                                                                                                                                                                                                                                                                                                               +
     FROM winner_events we                                                                                                                                                                                                                                                                                                                                                                                                          +
     -- Find other events where this artist competed                                                                                                                                                                                                                                                                                                                                                                                +
     JOIN event_artists ea ON ea.artist_id = we.artist_id                                                                                                                                                                                                                                                                                                                                                                           +
     JOIN events e2 ON e2.id = ea.event_id                                                                                                                                                                                                                                                                                                                                                                                          +
     JOIN cities c2 ON c2.id = e2.city_id                                                                                                                                                                                                                                                                                                                                                                                           +
     WHERE e2.event_start_datetime > we.event_start_datetime  -- Must be after the winning event                                                                                                                                                                                                                                                                                                                                    +
       AND e2.event_start_datetime <= we.event_start_datetime + interval '365 days'  -- Within 1 year                                                                                                                                                                                                                                                                                                                               +
       AND e2.id != we.event_id  -- Not the same event                                                                                                                                                                                                                                                                                                                                                                              +
       AND e2.event_start_datetime >= '2018-01-01'::timestamp                                                                                                                                                                                                                                                                                                                                                                       +
   )                                                                                                                                                                                                                                                                                                                                                                                                                                +
   -- Return results where the first event doesn't already have an advances_to relationship set                                                                                                                                                                                                                                                                                                                                     +
   SELECT                                                                                                                                                                                                                                                                                                                                                                                                                           +
     ane.artist_name,                                                                                                                                                                                                                                                                                                                                                                                                               +
     ane.artist_number,                                                                                                                                                                                                                                                                                                                                                                                                             +
     ane.first_event_eid,                                                                                                                                                                                                                                                                                                                                                                                                           +
     ane.first_event_name,                                                                                                                                                                                                                                                                                                                                                                                                          +
     ane.first_event_date,                                                                                                                                                                                                                                                                                                                                                                                                          +
     ane.first_event_city,                                                                                                                                                                                                                                                                                                                                                                                                          +
     ane.r3_votes,                                                                                                                                                                                                                                                                                                                                                                                                                  +
     ane.next_event_eid,                                                                                                                                                                                                                                                                                                                                                                                                            +
     ane.next_event_name,                                                                                                                                                                                                                                                                                                                                                                                                           +
     ane.next_event_date,                                                                                                                                                                                                                                                                                                                                                                                                           +
     ane.next_event_city,                                                                                                                                                                                                                                                                                                                                                                                                           +
     ane.days_between                                                                                                                                                                                                                                                                                                                                                                                                               +
   FROM artist_next_events ane                                                                                                                                                                                                                                                                                                                                                                                                      +
   JOIN events e ON e.eid = ane.first_event_eid                                                                                                                                                                                                                                                                                                                                                                                     +
   WHERE e.advances_to_event_eid IS NULL  -- Only show if relationship not already set                                                                                                                                                                                                                                                                                                                                              +
   ORDER BY ane.first_event_date DESC, ane.artist_name, ane.days_between;                                                                                                                                                                                                                                                                                                                                                           +
 END;                                                                                                                                                                                                                                                                                                                                                                                                                               +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                         +
 
(1 row)

