                                                                                                                                                               pg_get_functiondef                                                                                                                                                                
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_admin_payment_data(p_event_id uuid, p_user_phone text)                                                                                                                                                                                                                                                   +
  RETURNS TABLE(art_id uuid, art_code text, payment_log_id uuid, payment_type text, amount numeric, actual_amount_collected numeric, actual_tax_collected numeric, payment_method text, collection_notes text, admin_phone text, created_at timestamp with time zone, status_id uuid, payment_status_code text, payment_status_description text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                              +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                                  +
 DECLARE                                                                                                                                                                                                                                                                                                                                        +
   v_admin_level TEXT;                                                                                                                                                                                                                                                                                                                          +
 BEGIN                                                                                                                                                                                                                                                                                                                                          +
   -- Check admin level using existing function                                                                                                                                                                                                                                                                                                 +
   v_admin_level := get_user_admin_level(p_event_id, p_user_phone);                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                                                                +
   -- Only allow producer+ admins                                                                                                                                                                                                                                                                                                               +
   IF v_admin_level NOT IN ('super', 'producer') THEN                                                                                                                                                                                                                                                                                           +
     RAISE EXCEPTION 'Access denied. Producer+ admin access required.';                                                                                                                                                                                                                                                                         +
   END IF;                                                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                                                +
   -- Return payment data for event artworks                                                                                                                                                                                                                                                                                                    +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                                 +
   SELECT                                                                                                                                                                                                                                                                                                                                       +
     a.id as art_id,                                                                                                                                                                                                                                                                                                                            +
     a.art_code,                                                                                                                                                                                                                                                                                                                                +
     pl.id as payment_log_id,                                                                                                                                                                                                                                                                                                                   +
     pl.payment_type,                                                                                                                                                                                                                                                                                                                           +
     pl.amount,                                                                                                                                                                                                                                                                                                                                 +
     pl.actual_amount_collected,                                                                                                                                                                                                                                                                                                                +
     pl.actual_tax_collected,                                                                                                                                                                                                                                                                                                                   +
     pl.payment_method,                                                                                                                                                                                                                                                                                                                         +
     pl.collection_notes,                                                                                                                                                                                                                                                                                                                       +
     pl.admin_phone,                                                                                                                                                                                                                                                                                                                            +
     pl.created_at,                                                                                                                                                                                                                                                                                                                             +
     pl.status_id,                                                                                                                                                                                                                                                                                                                              +
     ps.code as payment_status_code,                                                                                                                                                                                                                                                                                                            +
     ps.description as payment_status_description                                                                                                                                                                                                                                                                                               +
   FROM art a                                                                                                                                                                                                                                                                                                                                   +
   LEFT JOIN payment_logs pl ON a.id = pl.art_id                                                                                                                                                                                                                                                                                                +
   LEFT JOIN payment_statuses ps ON pl.status_id = ps.id                                                                                                                                                                                                                                                                                        +
   WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                                                                                +
   AND pl.id IS NOT NULL  -- Only return artworks that have payment logs                                                                                                                                                                                                                                                                        +
   ORDER BY a.art_code, pl.created_at DESC;                                                                                                                                                                                                                                                                                                     +
 END;                                                                                                                                                                                                                                                                                                                                           +
 $function$                                                                                                                                                                                                                                                                                                                                     +
 
 CREATE OR REPLACE FUNCTION public.get_admin_payment_data(p_event_id uuid, p_user_id uuid, p_phone text)                                                                                                                                                                                                                                        +
  RETURNS TABLE(art_id uuid, art_code text, payment_log_id uuid, payment_type text, amount numeric, actual_amount_collected numeric, actual_tax_collected numeric, payment_method text, collection_notes text, admin_phone text, created_at timestamp with time zone, status_id uuid, payment_status_code text, payment_status_description text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                              +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                                  +
 DECLARE                                                                                                                                                                                                                                                                                                                                        +
   v_admin_level TEXT;                                                                                                                                                                                                                                                                                                                          +
 BEGIN                                                                                                                                                                                                                                                                                                                                          +
   -- Check admin level                                                                                                                                                                                                                                                                                                                         +
   v_admin_level := get_user_admin_level(p_user_id, p_phone);                                                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                                                                                                                +
   -- Only allow producer+ admins                                                                                                                                                                                                                                                                                                               +
   IF v_admin_level NOT IN ('super', 'producer') THEN                                                                                                                                                                                                                                                                                           +
     RAISE EXCEPTION 'Access denied. Producer+ admin access required.';                                                                                                                                                                                                                                                                         +
   END IF;                                                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                                                +
   -- Return payment data for event artworks                                                                                                                                                                                                                                                                                                    +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                                 +
   SELECT                                                                                                                                                                                                                                                                                                                                       +
     a.id as art_id,                                                                                                                                                                                                                                                                                                                            +
     a.art_code,                                                                                                                                                                                                                                                                                                                                +
     pl.id as payment_log_id,                                                                                                                                                                                                                                                                                                                   +
     pl.payment_type,                                                                                                                                                                                                                                                                                                                           +
     pl.amount,                                                                                                                                                                                                                                                                                                                                 +
     pl.actual_amount_collected,                                                                                                                                                                                                                                                                                                                +
     pl.actual_tax_collected,                                                                                                                                                                                                                                                                                                                   +
     pl.payment_method,                                                                                                                                                                                                                                                                                                                         +
     pl.collection_notes,                                                                                                                                                                                                                                                                                                                       +
     pl.admin_phone,                                                                                                                                                                                                                                                                                                                            +
     pl.created_at,                                                                                                                                                                                                                                                                                                                             +
     pl.status_id,                                                                                                                                                                                                                                                                                                                              +
     ps.code as payment_status_code,                                                                                                                                                                                                                                                                                                            +
     ps.description as payment_status_description                                                                                                                                                                                                                                                                                               +
   FROM art a                                                                                                                                                                                                                                                                                                                                   +
   LEFT JOIN payment_logs pl ON a.id = pl.art_id                                                                                                                                                                                                                                                                                                +
   LEFT JOIN payment_statuses ps ON pl.status_id = ps.id                                                                                                                                                                                                                                                                                        +
   WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                                                                                +
   AND pl.id IS NOT NULL  -- Only return artworks that have payment logs                                                                                                                                                                                                                                                                        +
   ORDER BY a.art_code, pl.created_at DESC;                                                                                                                                                                                                                                                                                                     +
 END;                                                                                                                                                                                                                                                                                                                                           +
 $function$                                                                                                                                                                                                                                                                                                                                     +
 
(2 rows)

