                                                                                                                                 pg_get_functiondef                                                                                                                                 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_payment_logs_admin(p_event_id uuid)                                                                                                                                                                                                         +
  RETURNS TABLE(art_id uuid, payment_log_id uuid, admin_phone text, created_at timestamp with time zone, payment_type character varying, actual_amount_collected numeric, actual_tax_collected numeric, payment_method text, collection_notes text, amount numeric, status_id uuid)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                 +
  SECURITY DEFINER                                                                                                                                                                                                                                                                 +
 AS $function$                                                                                                                                                                                                                                                                     +
 BEGIN                                                                                                                                                                                                                                                                             +
   -- Return payment logs for all artworks in this event                                                                                                                                                                                                                           +
   RETURN QUERY                                                                                                                                                                                                                                                                    +
   SELECT                                                                                                                                                                                                                                                                          +
     pl.art_id,                                                                                                                                                                                                                                                                    +
     pl.id as payment_log_id,                                                                                                                                                                                                                                                      +
     pl.admin_phone,                                                                                                                                                                                                                                                               +
     pl.created_at,                                                                                                                                                                                                                                                                +
     pl.payment_type,                                                                                                                                                                                                                                                              +
     pl.actual_amount_collected,                                                                                                                                                                                                                                                   +
     pl.actual_tax_collected,                                                                                                                                                                                                                                                      +
     pl.payment_method,                                                                                                                                                                                                                                                            +
     pl.collection_notes,                                                                                                                                                                                                                                                          +
     pl.amount,                                                                                                                                                                                                                                                                    +
     pl.status_id                                                                                                                                                                                                                                                                  +
   FROM payment_logs pl                                                                                                                                                                                                                                                            +
   JOIN art a ON a.id = pl.art_id                                                                                                                                                                                                                                                  +
   WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                   +
   ORDER BY pl.created_at DESC;                                                                                                                                                                                                                                                    +
 END;                                                                                                                                                                                                                                                                              +
 $function$                                                                                                                                                                                                                                                                        +
 
(1 row)

