                                                                                                                                 pg_get_functiondef                                                                                                                                 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_event_ready_to_pay(p_event_id uuid)                                                                                                                                                                                                         +
  RETURNS TABLE(artist_id uuid, artist_name text, artist_email text, artist_phone text, artist_entry_id integer, artist_country text, estimated_balance numeric, balance_currency text, stripe_recipient_id text, recent_city text, recent_contests integer, default_currency text)+
  LANGUAGE sql                                                                                                                                                                                                                                                                     +
  SECURITY DEFINER                                                                                                                                                                                                                                                                 +
  SET search_path TO 'public'                                                                                                                                                                                                                                                      +
 AS $function$                                                                                                                                                                                                                                                                     +
   WITH event_art_sales AS (                                                                                                                                                                                                                                                       +
     SELECT                                                                                                                                                                                                                                                                        +
       ap.id as artist_id,                                                                                                                                                                                                                                                         +
       e.currency,                                                                                                                                                                                                                                                                 +
       SUM(COALESCE(a.final_price, a.current_bid, 0) * 0.5) as sales_total                                                                                                                                                                                                         +
     FROM art a                                                                                                                                                                                                                                                                    +
     JOIN artist_profiles ap ON a.artist_id = ap.id                                                                                                                                                                                                                                +
     JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                            +
     WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                 +
       AND a.status = 'paid'                                                                                                                                                                                                                                                       +
       AND COALESCE(a.final_price, a.current_bid, 0) > 0                                                                                                                                                                                                                           +
     GROUP BY ap.id, e.currency                                                                                                                                                                                                                                                    +
   ),                                                                                                                                                                                                                                                                              +
   event_payment_debits AS (                                                                                                                                                                                                                                                       +
     SELECT                                                                                                                                                                                                                                                                        +
       ap.artist_profile_id,                                                                                                                                                                                                                                                       +
       ap.currency,                                                                                                                                                                                                                                                                +
       SUM(ap.gross_amount) as debits_total                                                                                                                                                                                                                                        +
     FROM artist_payments ap                                                                                                                                                                                                                                                       +
     JOIN art a ON ap.art_id = a.id                                                                                                                                                                                                                                                +
     WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                 +
       AND ap.status IN ('completed', 'paid')                                                                                                                                                                                                                                      +
     GROUP BY ap.artist_profile_id, ap.currency                                                                                                                                                                                                                                    +
   ),                                                                                                                                                                                                                                                                              +
   event_active_payment_attempts AS (                                                                                                                                                                                                                                              +
     SELECT DISTINCT                                                                                                                                                                                                                                                               +
       ap.artist_profile_id                                                                                                                                                                                                                                                        +
     FROM artist_payments ap                                                                                                                                                                                                                                                       +
     JOIN art a ON ap.art_id = a.id                                                                                                                                                                                                                                                +
     WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                 +
       AND ap.status NOT IN ('completed', 'paid')                                                                                                                                                                                                                                  +
       AND ap.created_at >= NOW() - INTERVAL '7 days'                                                                                                                                                                                                                              +
   ),                                                                                                                                                                                                                                                                              +
   event_participants AS (                                                                                                                                                                                                                                                         +
     SELECT DISTINCT                                                                                                                                                                                                                                                               +
       rc.artist_id                                                                                                                                                                                                                                                                +
     FROM round_contestants rc                                                                                                                                                                                                                                                     +
     JOIN rounds r ON rc.round_id = r.id                                                                                                                                                                                                                                           +
     WHERE r.event_id = p_event_id                                                                                                                                                                                                                                                 +
   )                                                                                                                                                                                                                                                                               +
   SELECT                                                                                                                                                                                                                                                                          +
     ap.id as artist_id,                                                                                                                                                                                                                                                           +
     ap.name::text as artist_name,                                                                                                                                                                                                                                                 +
     ap.email::text as artist_email,                                                                                                                                                                                                                                               +
     ap.phone::text as artist_phone,                                                                                                                                                                                                                                               +
     ap.entry_id as artist_entry_id,                                                                                                                                                                                                                                               +
     ap.country::text as artist_country,                                                                                                                                                                                                                                           +
     GREATEST(0, COALESCE(asales.sales_total, 0) - COALESCE(pd.debits_total, 0)) as estimated_balance,                                                                                                                                                                             +
     COALESCE(ev.currency, 'USD') as balance_currency,                                                                                                                                                                                                                             +
     agp.stripe_recipient_id::text,                                                                                                                                                                                                                                                +
     ev.name::text as recent_city,                                                                                                                                                                                                                                                 +
     1 as recent_contests,                                                                                                                                                                                                                                                         +
     agp.default_currency::text                                                                                                                                                                                                                                                    +
   FROM artist_profiles ap                                                                                                                                                                                                                                                         +
   JOIN event_participants ep ON ap.id = ep.artist_id                                                                                                                                                                                                                              +
   LEFT JOIN event_art_sales asales ON ap.id = asales.artist_id                                                                                                                                                                                                                    +
   LEFT JOIN event_payment_debits pd ON ap.id = pd.artist_profile_id                                                                                                                                                                                                               +
   LEFT JOIN events ev ON ev.id = p_event_id                                                                                                                                                                                                                                       +
   JOIN artist_global_payments agp ON ap.id = agp.artist_profile_id                                                                                                                                                                                                                +
   LEFT JOIN event_active_payment_attempts eapa ON ap.id = eapa.artist_profile_id                                                                                                                                                                                                  +
   WHERE GREATEST(0, COALESCE(asales.sales_total, 0) - COALESCE(pd.debits_total, 0)) > 0.01                                                                                                                                                                                        +
     AND agp.status = 'ready'                                                                                                                                                                                                                                                      +
     AND agp.stripe_recipient_id IS NOT NULL                                                                                                                                                                                                                                       +
     AND LENGTH(agp.stripe_recipient_id) > 0                                                                                                                                                                                                                                       +
     AND eapa.artist_profile_id IS NULL  -- Exclude artists with recent payment attempts                                                                                                                                                                                           +
   ORDER BY estimated_balance DESC;                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                        +
 
(1 row)

