                                                                                                                                                                  pg_get_functiondef                                                                                                                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_event_art_status(p_event_id uuid)                                                                                                                                                                                                                                                                              +
  RETURNS TABLE(art_id uuid, art_code text, artist_name text, artist_email text, title text, current_bid numeric, final_price numeric, art_status text, currency text, sold_date timestamp with time zone, payment_status text, payment_date timestamp with time zone, days_since_sale integer, needs_reminder boolean, needs_runner_up_offer boolean)+
  LANGUAGE sql                                                                                                                                                                                                                                                                                                                                        +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                    +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                                                                                                                                                        +
   SELECT                                                                                                                                                                                                                                                                                                                                             +
     a.id as art_id,                                                                                                                                                                                                                                                                                                                                  +
     a.art_code,                                                                                                                                                                                                                                                                                                                                      +
     ap.name as artist_name,                                                                                                                                                                                                                                                                                                                          +
     ap.email as artist_email,                                                                                                                                                                                                                                                                                                                        +
     a.description as title,                                                                                                                                                                                                                                                                                                                          +
     a.current_bid,                                                                                                                                                                                                                                                                                                                                   +
     a.final_price,                                                                                                                                                                                                                                                                                                                                   +
     a.status as art_status,                                                                                                                                                                                                                                                                                                                          +
     e.currency,                                                                                                                                                                                                                                                                                                                                      +
     a.buyer_pay_recent_date as sold_date,                                                                                                                                                                                                                                                                                                            +
     CASE                                                                                                                                                                                                                                                                                                                                             +
       WHEN a.status = 'paid' THEN 'paid'                                                                                                                                                                                                                                                                                                             +
       WHEN a.status = 'sold' THEN 'unpaid'                                                                                                                                                                                                                                                                                                           +
       ELSE 'no_sale'                                                                                                                                                                                                                                                                                                                                 +
     END as payment_status,                                                                                                                                                                                                                                                                                                                           +
     a.buyer_pay_recent_date as payment_date,                                                                                                                                                                                                                                                                                                         +
     CASE                                                                                                                                                                                                                                                                                                                                             +
       WHEN a.buyer_pay_recent_date IS NOT NULL THEN                                                                                                                                                                                                                                                                                                  +
         EXTRACT(DAY FROM NOW() - a.buyer_pay_recent_date)::integer                                                                                                                                                                                                                                                                                   +
       ELSE NULL                                                                                                                                                                                                                                                                                                                                      +
     END as days_since_sale,                                                                                                                                                                                                                                                                                                                          +
     -- Needs reminder if sold but not paid for more than 3 days                                                                                                                                                                                                                                                                                      +
     (a.status = 'sold' AND                                                                                                                                                                                                                                                                                                                           +
      a.buyer_pay_recent_date IS NOT NULL AND                                                                                                                                                                                                                                                                                                         +
      a.buyer_pay_recent_date < NOW() - INTERVAL '3 days') as needs_reminder,                                                                                                                                                                                                                                                                         +
     -- Needs runner-up offer if sold but not paid for more than 7 days                                                                                                                                                                                                                                                                               +
     (a.status = 'sold' AND                                                                                                                                                                                                                                                                                                                           +
      a.buyer_pay_recent_date IS NOT NULL AND                                                                                                                                                                                                                                                                                                         +
      a.buyer_pay_recent_date < NOW() - INTERVAL '7 days') as needs_runner_up_offer                                                                                                                                                                                                                                                                   +
   FROM art a                                                                                                                                                                                                                                                                                                                                         +
   JOIN artist_profiles ap ON a.artist_id = ap.id                                                                                                                                                                                                                                                                                                     +
   JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                                                                 +
   WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                                                                                      +
     AND a.status IN ('sold', 'paid', 'closed')                                                                                                                                                                                                                                                                                                       +
     AND COALESCE(a.final_price, a.current_bid, 0) > 0                                                                                                                                                                                                                                                                                                +
   ORDER BY                                                                                                                                                                                                                                                                                                                                           +
     CASE WHEN a.status = 'sold' THEN 1 ELSE 2 END,  -- Unpaid first                                                                                                                                                                                                                                                                                  +
     a.buyer_pay_recent_date DESC NULLS LAST;                                                                                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                                                                                                           +
 
(1 row)

