                                                                                                            pg_get_functiondef                                                                                                            
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_artwork_payment_race_status(p_art_id uuid)                                                                                                                                                        +
  RETURNS TABLE(artwork_status text, winner_id uuid, current_bid numeric, has_active_offers boolean, active_offer_count integer, pending_payments integer, processing_payments integer, completed_payments integer, offers_summary jsonb)+
  LANGUAGE plpgsql                                                                                                                                                                                                                       +
  SECURITY DEFINER                                                                                                                                                                                                                       +
 AS $function$                                                                                                                                                                                                                           +
 BEGIN                                                                                                                                                                                                                                   +
   RETURN QUERY                                                                                                                                                                                                                          +
   SELECT                                                                                                                                                                                                                                +
     a.status::text,                                                                                                                                                                                                                     +
     a.winner_id,                                                                                                                                                                                                                        +
     a.current_bid,                                                                                                                                                                                                                      +
     EXISTS(                                                                                                                                                                                                                             +
       SELECT 1 FROM artwork_offers ao                                                                                                                                                                                                   +
       WHERE ao.art_id = p_art_id                                                                                                                                                                                                        +
       AND ao.status = 'pending'                                                                                                                                                                                                         +
       AND ao.expires_at > NOW()                                                                                                                                                                                                         +
     ) as has_active_offers,                                                                                                                                                                                                             +
     (                                                                                                                                                                                                                                   +
       SELECT COUNT(*)::INTEGER                                                                                                                                                                                                          +
       FROM artwork_offers ao                                                                                                                                                                                                            +
       WHERE ao.art_id = p_art_id                                                                                                                                                                                                        +
       AND ao.status = 'pending'                                                                                                                                                                                                         +
       AND ao.expires_at > NOW()                                                                                                                                                                                                         +
     ) as active_offer_count,                                                                                                                                                                                                            +
     (                                                                                                                                                                                                                                   +
       SELECT COUNT(*)::INTEGER                                                                                                                                                                                                          +
       FROM payment_processing pp                                                                                                                                                                                                        +
       WHERE pp.art_id = p_art_id                                                                                                                                                                                                        +
       AND pp.status = 'pending'                                                                                                                                                                                                         +
     ) as pending_payments,                                                                                                                                                                                                              +
     (                                                                                                                                                                                                                                   +
       SELECT COUNT(*)::INTEGER                                                                                                                                                                                                          +
       FROM payment_processing pp                                                                                                                                                                                                        +
       WHERE pp.art_id = p_art_id                                                                                                                                                                                                        +
       AND pp.status = 'processing'                                                                                                                                                                                                      +
     ) as processing_payments,                                                                                                                                                                                                           +
     (                                                                                                                                                                                                                                   +
       SELECT COUNT(*)::INTEGER                                                                                                                                                                                                          +
       FROM payment_processing pp                                                                                                                                                                                                        +
       WHERE pp.art_id = p_art_id                                                                                                                                                                                                        +
       AND pp.status = 'completed'                                                                                                                                                                                                       +
     ) as completed_payments,                                                                                                                                                                                                            +
     (                                                                                                                                                                                                                                   +
       SELECT COALESCE(jsonb_agg(                                                                                                                                                                                                        +
         jsonb_build_object(                                                                                                                                                                                                             +
           'offer_id', ao.id,                                                                                                                                                                                                            +
           'person_id', ao.offered_to_person_id,                                                                                                                                                                                         +
           'person_name', COALESCE(p.first_name || ' ' || p.last_name, p.name),                                                                                                                                                          +
           'offered_amount', ao.offered_amount,                                                                                                                                                                                          +
           'expires_at', ao.expires_at,                                                                                                                                                                                                  +
           'minutes_remaining', EXTRACT(EPOCH FROM (ao.expires_at - NOW()))/60                                                                                                                                                           +
         )                                                                                                                                                                                                                               +
       ), '[]'::jsonb)                                                                                                                                                                                                                   +
       FROM artwork_offers ao                                                                                                                                                                                                            +
       LEFT JOIN people p ON ao.offered_to_person_id = p.id                                                                                                                                                                              +
       WHERE ao.art_id = p_art_id                                                                                                                                                                                                        +
       AND ao.status = 'pending'                                                                                                                                                                                                         +
       AND ao.expires_at > NOW()                                                                                                                                                                                                         +
     ) as offers_summary                                                                                                                                                                                                                 +
   FROM art a                                                                                                                                                                                                                            +
   WHERE a.id = p_art_id;                                                                                                                                                                                                                +
 END;                                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                              +
 
(1 row)

