                                                                                                                pg_get_functiondef                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_overdue_artist_payments(days_threshold integer DEFAULT 14)                                                                                                                                                +
  RETURNS TABLE(artist_id uuid, artist_name text, artist_email text, artist_phone text, artist_entry_id integer, balance_owed numeric, currency text, days_overdue integer, reference_date timestamp with time zone, payment_account_status text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                               +
  STABLE                                                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                                                   +
 BEGIN                                                                                                                                                                                                                                           +
   RETURN QUERY                                                                                                                                                                                                                                  +
   SELECT                                                                                                                                                                                                                                        +
     a.artist_id,                                                                                                                                                                                                                                +
     a.artist_name,                                                                                                                                                                                                                              +
     a.artist_email,                                                                                                                                                                                                                             +
     a.artist_phone,                                                                                                                                                                                                                             +
     a.artist_entry_id,                                                                                                                                                                                                                          +
     a.estimated_balance as balance_owed,                                                                                                                                                                                                        +
     a.balance_currency as currency,                                                                                                                                                                                                             +
     EXTRACT(DAY FROM (NOW() - ref.ref_date))::INTEGER as days_overdue,                                                                                                                                                                          +
     ref.ref_date as reference_date,                                                                                                                                                                                                             +
     a.payment_account_status                                                                                                                                                                                                                    +
   FROM get_artists_owed() a                                                                                                                                                                                                                     +
   CROSS JOIN LATERAL (                                                                                                                                                                                                                          +
     SELECT COALESCE(                                                                                                                                                                                                                            +
       MAX(art.buyer_pay_recent_date),                                                                                                                                                                                                           +
       MAX(e.event_end_datetime)                                                                                                                                                                                                                 +
     ) as ref_date                                                                                                                                                                                                                               +
     FROM art                                                                                                                                                                                                                                    +
     JOIN events e ON art.event_id = e.id                                                                                                                                                                                                        +
     WHERE art.artist_id = a.artist_id                                                                                                                                                                                                           +
       AND art.status IN ('sold', 'paid')                                                                                                                                                                                                        +
   ) ref                                                                                                                                                                                                                                         +
   WHERE ref.ref_date < NOW() - (days_threshold || ' days')::INTERVAL                                                                                                                                                                            +
     AND a.estimated_balance > 0.01                                                                                                                                                                                                              +
   ORDER BY days_overdue DESC;                                                                                                                                                                                                                   +
 END;                                                                                                                                                                                                                                            +
 $function$                                                                                                                                                                                                                                      +
 
(1 row)

