                                                                                                          pg_get_functiondef                                                                                                           
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_global_payment_status(p_art_id uuid)                                                                                                                                                           +
  RETURNS TABLE(payment_status text, amount_minor bigint, currency character varying, sent_at timestamp with time zone, paid_at timestamp with time zone, has_buyer_payment boolean, buyer_payment_status text, stripe_payout_id text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                    +
 AS $function$                                                                                                                                                                                                                        +
 BEGIN                                                                                                                                                                                                                                +
     RETURN QUERY                                                                                                                                                                                                                     +
     SELECT                                                                                                                                                                                                                           +
         COALESCE(gpr.status, 'no_payment') as payment_status,                                                                                                                                                                        +
         gpr.amount_minor,                                                                                                                                                                                                            +
         gpr.currency,                                                                                                                                                                                                                +
         gpr.sent_at,                                                                                                                                                                                                                 +
         gpr.paid_at,                                                                                                                                                                                                                 +
         (pp.id IS NOT NULL) as has_buyer_payment,                                                                                                                                                                                    +
         pp.status as buyer_payment_status,                                                                                                                                                                                           +
         gpr.stripe_payout_id                                                                                                                                                                                                         +
     FROM art a                                                                                                                                                                                                                       +
     LEFT JOIN global_payment_requests gpr ON gpr.art_id = a.id                                                                                                                                                                       +
     LEFT JOIN payment_processing pp ON pp.art_id = a.id AND pp.status = 'completed'                                                                                                                                                  +
     WHERE a.id = p_art_id;                                                                                                                                                                                                           +
 END;                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                           +
 
(1 row)

