                                                                                                             pg_get_functiondef                                                                                                              
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_event_vote_ranges(p_event_id uuid)                                                                                                                                                                   +
  RETURNS TABLE(art_id uuid, range_0_22 integer, range_0_95 integer, range_1_01 integer, range_1_90 integer, range_2_50 integer, range_5_01 integer, range_10_00 integer, range_above_10 integer, total_weight numeric, total_votes integer)+
  LANGUAGE plpgsql                                                                                                                                                                                                                          +
  STABLE                                                                                                                                                                                                                                    +
  SET search_path TO 'pg_catalog', 'public'                                                                                                                                                                                                 +
 AS $function$                                                                                                                                                                                                                              +
 BEGIN                                                                                                                                                                                                                                      +
   RETURN QUERY                                                                                                                                                                                                                             +
   SELECT                                                                                                                                                                                                                                   +
     v.art_uuid as art_id,                                                                                                                                                                                                                  +
     COUNT(CASE WHEN v.vote_factor <= 0.22 THEN 1 END)::INTEGER as range_0_22,                                                                                                                                                              +
     COUNT(CASE WHEN v.vote_factor > 0.22 AND v.vote_factor <= 0.95 THEN 1 END)::INTEGER as range_0_95,                                                                                                                                     +
     COUNT(CASE WHEN v.vote_factor > 0.95 AND v.vote_factor <= 1.01 THEN 1 END)::INTEGER as range_1_01,                                                                                                                                     +
     COUNT(CASE WHEN v.vote_factor > 1.01 AND v.vote_factor <= 1.90 THEN 1 END)::INTEGER as range_1_90,                                                                                                                                     +
     COUNT(CASE WHEN v.vote_factor > 1.90 AND v.vote_factor <= 2.50 THEN 1 END)::INTEGER as range_2_50,                                                                                                                                     +
     COUNT(CASE WHEN v.vote_factor > 2.50 AND v.vote_factor <= 5.01 THEN 1 END)::INTEGER as range_5_01,                                                                                                                                     +
     COUNT(CASE WHEN v.vote_factor > 5.01 AND v.vote_factor <= 10.00 THEN 1 END)::INTEGER as range_10_00,                                                                                                                                   +
     COUNT(CASE WHEN v.vote_factor > 10.00 THEN 1 END)::INTEGER as range_above_10,                                                                                                                                                          +
     COALESCE(SUM(v.vote_factor), 0) as total_weight,                                                                                                                                                                                       +
     COUNT(*)::INTEGER as total_votes                                                                                                                                                                                                       +
   FROM votes v                                                                                                                                                                                                                             +
   WHERE v.event_id = p_event_id                                                                                                                                                                                                            +
     AND v.art_uuid IS NOT NULL                                                                                                                                                                                                             +
   GROUP BY v.art_uuid                                                                                                                                                                                                                      +
   ORDER BY total_weight DESC;                                                                                                                                                                                                              +
 END;                                                                                                                                                                                                                                       +
 $function$                                                                                                                                                                                                                                 +
 
(1 row)

