                                                                                                              pg_get_functiondef                                                                                                              
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_pending_payments_for_processing(batch_limit integer DEFAULT 10)                                                                                                                                       +
  RETURNS TABLE(id uuid, artist_profile_id uuid, artist_name text, artist_email text, gross_amount numeric, currency character varying, description text, stripe_recipient_id text, payment_status text, created_at timestamp with time zone)+
  LANGUAGE plpgsql                                                                                                                                                                                                                           +
  SECURITY DEFINER                                                                                                                                                                                                                           +
  SET search_path TO 'public'                                                                                                                                                                                                                +
 AS $function$                                                                                                                                                                                                                               +
 BEGIN                                                                                                                                                                                                                                       +
     RETURN QUERY                                                                                                                                                                                                                            +
     SELECT                                                                                                                                                                                                                                  +
         apm.id,                                                                                                                                                                                                                             +
         apm.artist_profile_id,                                                                                                                                                                                                              +
         ap.name as artist_name,                                                                                                                                                                                                             +
         ap.email as artist_email,                                                                                                                                                                                                           +
         apm.gross_amount,                                                                                                                                                                                                                   +
         apm.currency,                                                                                                                                                                                                                       +
         apm.description,                                                                                                                                                                                                                    +
         agp.stripe_recipient_id,                                                                                                                                                                                                            +
         agp.status as payment_status,                                                                                                                                                                                                       +
         apm.created_at                                                                                                                                                                                                                      +
     FROM artist_payments apm                                                                                                                                                                                                                +
     JOIN artist_profiles ap ON apm.artist_profile_id = ap.id                                                                                                                                                                                +
     JOIN artist_global_payments agp ON ap.id = agp.artist_profile_id                                                                                                                                                                        +
     WHERE                                                                                                                                                                                                                                   +
         -- Only automated payments (not manual)                                                                                                                                                                                             +
         apm.payment_type = 'automated'                                                                                                                                                                                                      +
         -- Only pending or processing status                                                                                                                                                                                                +
         AND apm.status IN ('pending', 'processing')                                                                                                                                                                                         +
         -- Only artists with Global Payments accounts                                                                                                                                                                                       +
         AND agp.stripe_recipient_id IS NOT NULL                                                                                                                                                                                             +
         -- Only ready payment accounts                                                                                                                                                                                                      +
         AND agp.status = 'ready'                                                                                                                                                                                                            +
         -- Order by oldest first                                                                                                                                                                                                            +
     ORDER BY apm.created_at ASC                                                                                                                                                                                                             +
     LIMIT batch_limit;                                                                                                                                                                                                                      +
 END;                                                                                                                                                                                                                                        +
 $function$                                                                                                                                                                                                                                  +
 
(1 row)

