                                                                                                              pg_get_functiondef                                                                                                               
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_pending_admin_invitations(expiry_threshold_hours integer DEFAULT 2)                                                                                                                                    +
  RETURNS TABLE(id uuid, email text, level text, invitation_sent_at timestamp with time zone, invitation_expires_at timestamp with time zone, hours_until_expiry numeric, reminder_count integer, last_reminder_sent timestamp with time zone)+
  LANGUAGE plpgsql                                                                                                                                                                                                                            +
  SECURITY DEFINER                                                                                                                                                                                                                            +
 AS $function$                                                                                                                                                                                                                                +
 BEGIN                                                                                                                                                                                                                                        +
   RETURN QUERY                                                                                                                                                                                                                               +
   SELECT                                                                                                                                                                                                                                     +
     au.id,                                                                                                                                                                                                                                   +
     au.email,                                                                                                                                                                                                                                +
     au.level,                                                                                                                                                                                                                                +
     au.invitation_sent_at,                                                                                                                                                                                                                   +
     au.invitation_expires_at,                                                                                                                                                                                                                +
     ROUND(EXTRACT(EPOCH FROM (au.invitation_expires_at - NOW())) / 3600, 1) as hours_until_expiry,                                                                                                                                           +
     COALESCE(au.invitation_reminder_count, 0) as reminder_count,                                                                                                                                                                             +
     au.last_invitation_reminder_sent                                                                                                                                                                                                         +
   FROM abhq_admin_users au                                                                                                                                                                                                                   +
   WHERE au.active = false                                                                                                                                                                                                                    +
     AND au.invitation_sent_at IS NOT NULL                                                                                                                                                                                                    +
     AND au.invitation_expires_at > NOW()                                                                                                                                                                                                     +
     AND au.invitation_expires_at <= NOW() + INTERVAL '1 hour' * expiry_threshold_hours                                                                                                                                                       +
   ORDER BY au.invitation_expires_at ASC;                                                                                                                                                                                                     +
 END;                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                   +
 
(1 row)

