                                                                                                                                                                                                                                  pg_get_functiondef                                                                                                                                                                                                                                  
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_latest_eventbrite_cache(p_eid character varying)                                                                                                                                                                                                                                                                                                                                                                                              +
  RETURNS TABLE(cache_id uuid, event_id uuid, eid character varying, total_tickets_sold integer, gross_revenue numeric, ticket_revenue numeric, taxes_collected numeric, eventbrite_fees numeric, payment_processing_fees numeric, total_fees numeric, net_deposit numeric, currency_code character varying, data_quality_score integer, is_stale boolean, fetched_at timestamp without time zone, expires_at timestamp without time zone, sales_summary jsonb, ticket_classes jsonb)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                       +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                               +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
   SELECT                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
     eac.id as cache_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                             +
     eac.event_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
     eac.eid,                                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
     eac.total_tickets_sold,                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
     eac.gross_revenue,                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
     eac.ticket_revenue,                                                                                                                                                                                                                                                                                                                                                                                                                                                             +
     eac.taxes_collected,                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
     eac.eventbrite_fees,                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
     eac.payment_processing_fees,                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
     eac.total_fees,                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
     eac.net_deposit,                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
     eac.currency_code,                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
     eac.data_quality_score,                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
     eac.is_stale,                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
     eac.fetched_at,                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
     eac.expires_at,                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
     eac.sales_summary,                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
     eac.ticket_classes                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
   FROM eventbrite_api_cache eac                                                                                                                                                                                                                                                                                                                                                                                                                                                     +
   WHERE eac.eid = p_eid                                                                                                                                                                                                                                                                                                                                                                                                                                                             +
   ORDER BY eac.fetched_at DESC                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
   LIMIT 1;                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
 END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                          +
 
(1 row)

