                                                                                                                                                                                        pg_get_functiondef                                                                                                                                                                                         
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_event_payment_attempts(p_event_id uuid, p_days_back integer DEFAULT 30)                                                                                                                                                                                                                                                                                    +
  RETURNS TABLE(artist_id uuid, artist_name text, artist_email text, artist_phone text, artist_entry_id integer, artist_country text, payment_id uuid, payment_amount numeric, payment_currency text, payment_status text, payment_method text, payment_type text, payment_date timestamp with time zone, stripe_transfer_id text, stripe_recipient_id text, error_message text, recent_city text)+
  LANGUAGE sql                                                                                                                                                                                                                                                                                                                                                                                    +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                                                                     +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                    +
   SELECT                                                                                                                                                                                                                                                                                                                                                                                         +
     ap.id as artist_id,                                                                                                                                                                                                                                                                                                                                                                          +
     ap.name as artist_name,                                                                                                                                                                                                                                                                                                                                                                      +
     ap.email as artist_email,                                                                                                                                                                                                                                                                                                                                                                    +
     ap.phone as artist_phone,                                                                                                                                                                                                                                                                                                                                                                    +
     ap.entry_id as artist_entry_id,                                                                                                                                                                                                                                                                                                                                                              +
     ap.country as artist_country,                                                                                                                                                                                                                                                                                                                                                                +
     apt.id as payment_id,                                                                                                                                                                                                                                                                                                                                                                        +
     apt.gross_amount as payment_amount,                                                                                                                                                                                                                                                                                                                                                          +
     apt.currency as payment_currency,                                                                                                                                                                                                                                                                                                                                                            +
     apt.status as payment_status,                                                                                                                                                                                                                                                                                                                                                                +
     apt.payment_method,                                                                                                                                                                                                                                                                                                                                                                          +
     apt.payment_type,                                                                                                                                                                                                                                                                                                                                                                            +
     apt.created_at as payment_date,                                                                                                                                                                                                                                                                                                                                                              +
     apt.stripe_transfer_id,                                                                                                                                                                                                                                                                                                                                                                      +
     agp.stripe_recipient_id,                                                                                                                                                                                                                                                                                                                                                                     +
     apt.error_message,                                                                                                                                                                                                                                                                                                                                                                           +
     e.name as recent_city                                                                                                                                                                                                                                                                                                                                                                        +
   FROM artist_payments apt                                                                                                                                                                                                                                                                                                                                                                       +
   JOIN artist_profiles ap ON apt.artist_profile_id = ap.id                                                                                                                                                                                                                                                                                                                                       +
   LEFT JOIN artist_global_payments agp ON ap.id = agp.artist_profile_id                                                                                                                                                                                                                                                                                                                          +
   LEFT JOIN events e ON e.id = p_event_id                                                                                                                                                                                                                                                                                                                                                        +
   JOIN art a ON apt.art_id = a.id                                                                                                                                                                                                                                                                                                                                                                +
   WHERE a.event_id = p_event_id                                                                                                                                                                                                                                                                                                                                                                  +
     AND apt.status NOT IN ('completed', 'paid', 'verified', 'cancelled')                                                                                                                                                                                                                                                                                                                         +
     AND apt.created_at >= NOW() - make_interval(days => p_days_back)                                                                                                                                                                                                                                                                                                                             +
   ORDER BY apt.created_at DESC;                                                                                                                                                                                                                                                                                                                                                                  +
 $function$                                                                                                                                                                                                                                                                                                                                                                                       +
 
(1 row)

