                                                                                                                                                                                                 pg_get_functiondef                                                                                                                                                                                                 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_event_payment_summary(p_event_id uuid)                                                                                                                                                                                                                                                                                                                                      +
  RETURNS TABLE(event_name text, event_currency text, total_art_pieces integer, sold_art_pieces integer, paid_art_pieces integer, unpaid_art_pieces integer, total_sales_amount numeric, total_artist_earnings numeric, total_payments_made numeric, outstanding_artist_payments numeric, artists_owed_count integer, artists_ready_to_pay_count integer, payment_attempts_count integer, currency_breakdown jsonb)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                 +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                 +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                                                                                      +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                     +
 DECLARE                                                                                                                                                                                                                                                                                                                                                                                                           +
     v_event_name text;                                                                                                                                                                                                                                                                                                                                                                                            +
     v_event_currency text;                                                                                                                                                                                                                                                                                                                                                                                        +
     v_currency_breakdown jsonb;                                                                                                                                                                                                                                                                                                                                                                                   +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                             +
     -- Get event info                                                                                                                                                                                                                                                                                                                                                                                             +
     SELECT e.name, e.currency                                                                                                                                                                                                                                                                                                                                                                                     +
     INTO v_event_name, v_event_currency                                                                                                                                                                                                                                                                                                                                                                           +
     FROM events e                                                                                                                                                                                                                                                                                                                                                                                                 +
     WHERE e.id = p_event_id;                                                                                                                                                                                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                                                                                                                                                                                   +
     -- Calculate currency breakdown                                                                                                                                                                                                                                                                                                                                                                               +
     SELECT jsonb_object_agg(                                                                                                                                                                                                                                                                                                                                                                                      +
         currency_data.currency,                                                                                                                                                                                                                                                                                                                                                                                   +
         jsonb_build_object(                                                                                                                                                                                                                                                                                                                                                                                       +
             'artists_count', currency_data.artists_count,                                                                                                                                                                                                                                                                                                                                                         +
             'total_owed', currency_data.total_owed                                                                                                                                                                                                                                                                                                                                                                +
         )                                                                                                                                                                                                                                                                                                                                                                                                         +
     )                                                                                                                                                                                                                                                                                                                                                                                                             +
     INTO v_currency_breakdown                                                                                                                                                                                                                                                                                                                                                                                     +
     FROM (                                                                                                                                                                                                                                                                                                                                                                                                        +
         SELECT                                                                                                                                                                                                                                                                                                                                                                                                    +
             COALESCE(eao.balance_currency, 'USD') as currency,                                                                                                                                                                                                                                                                                                                                                    +
             COUNT(*) as artists_count,                                                                                                                                                                                                                                                                                                                                                                            +
             SUM(eao.estimated_balance) as total_owed                                                                                                                                                                                                                                                                                                                                                              +
         FROM get_event_artists_owed(p_event_id) eao                                                                                                                                                                                                                                                                                                                                                               +
         GROUP BY eao.balance_currency                                                                                                                                                                                                                                                                                                                                                                             +
     ) currency_data;                                                                                                                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                                                                                                                                   +
     RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                  +
     SELECT                                                                                                                                                                                                                                                                                                                                                                                                        +
         v_event_name,                                                                                                                                                                                                                                                                                                                                                                                             +
         v_event_currency,                                                                                                                                                                                                                                                                                                                                                                                         +
         -- Art piece counts                                                                                                                                                                                                                                                                                                                                                                                       +
         (SELECT COUNT(*)::integer FROM art WHERE event_id = p_event_id) as total_art_pieces,                                                                                                                                                                                                                                                                                                                      +
         (SELECT COUNT(*)::integer FROM art WHERE event_id = p_event_id AND status IN ('sold', 'paid')) as sold_art_pieces,                                                                                                                                                                                                                                                                                        +
         (SELECT COUNT(*)::integer FROM art WHERE event_id = p_event_id AND status = 'paid') as paid_art_pieces,                                                                                                                                                                                                                                                                                                   +
         (SELECT COUNT(*)::integer FROM art WHERE event_id = p_event_id AND status = 'sold') as unpaid_art_pieces,                                                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                                                                                                                                                   +
         -- Financial amounts                                                                                                                                                                                                                                                                                                                                                                                      +
         (SELECT COALESCE(SUM(COALESCE(final_price, current_bid, 0)), 0)                                                                                                                                                                                                                                                                                                                                           +
          FROM art WHERE event_id = p_event_id AND status IN ('sold', 'paid')) as total_sales_amount,                                                                                                                                                                                                                                                                                                              +
         (SELECT COALESCE(SUM(COALESCE(final_price, current_bid, 0) * 0.5), 0)                                                                                                                                                                                                                                                                                                                                     +
          FROM art WHERE event_id = p_event_id AND status = 'paid') as total_artist_earnings,                                                                                                                                                                                                                                                                                                                      +
         (SELECT COALESCE(SUM(ap.gross_amount), 0)                                                                                                                                                                                                                                                                                                                                                                 +
          FROM artist_payments ap                                                                                                                                                                                                                                                                                                                                                                                  +
          JOIN art a ON ap.art_id = a.id                                                                                                                                                                                                                                                                                                                                                                           +
          WHERE a.event_id = p_event_id AND ap.status IN ('completed', 'paid', 'verified')) as total_payments_made,                                                                                                                                                                                                                                                                                                +
         (SELECT COALESCE(SUM(eao.estimated_balance), 0)                                                                                                                                                                                                                                                                                                                                                           +
          FROM get_event_artists_owed(p_event_id) eao) as outstanding_artist_payments,                                                                                                                                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                                                                                                                                                                   +
         -- Counts                                                                                                                                                                                                                                                                                                                                                                                                 +
         (SELECT COUNT(*)::integer FROM get_event_artists_owed(p_event_id)) as artists_owed_count,                                                                                                                                                                                                                                                                                                                 +
         (SELECT COUNT(*)::integer FROM get_event_ready_to_pay(p_event_id)) as artists_ready_to_pay_count,                                                                                                                                                                                                                                                                                                         +
         (SELECT COUNT(*)::integer FROM get_event_payment_attempts(p_event_id, 30)) as payment_attempts_count,                                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                                                                                                                                                   +
         -- Currency breakdown                                                                                                                                                                                                                                                                                                                                                                                     +
         COALESCE(v_currency_breakdown, '{}'::jsonb) as currency_breakdown;                                                                                                                                                                                                                                                                                                                                        +
 END;                                                                                                                                                                                                                                                                                                                                                                                                              +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                        +
 
(1 row)

