                                                                                                                     pg_get_functiondef                                                                                                                      
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_ready_to_pay_artists()                                                                                                                                                                                               +
  RETURNS TABLE(artist_id uuid, artist_name text, artist_email text, artist_phone text, artist_entry_id integer, artist_country text, estimated_balance numeric, stripe_recipient_id text, recent_city text, recent_contests integer, default_currency text)+
  LANGUAGE sql                                                                                                                                                                                                                                              +
  SECURITY DEFINER                                                                                                                                                                                                                                          +
  SET search_path TO 'public'                                                                                                                                                                                                                               +
 AS $function$                                                                                                                                                                                                                                              +
   WITH art_sales AS (                                                                                                                                                                                                                                      +
     SELECT                                                                                                                                                                                                                                                 +
       ap.id as artist_id,                                                                                                                                                                                                                                  +
       SUM(COALESCE(a.final_price, a.current_bid, 0) * 0.5) as sales_total                                                                                                                                                                                  +
     FROM art a                                                                                                                                                                                                                                             +
     JOIN artist_profiles ap ON a.artist_id = ap.id                                                                                                                                                                                                         +
     WHERE a.status IN ('sold', 'paid', 'closed')                                                                                                                                                                                                           +
       AND COALESCE(a.final_price, a.current_bid, 0) > 0                                                                                                                                                                                                    +
     GROUP BY ap.id                                                                                                                                                                                                                                         +
   ),                                                                                                                                                                                                                                                       +
   payment_debits AS (                                                                                                                                                                                                                                      +
     SELECT                                                                                                                                                                                                                                                 +
       ap.artist_profile_id,                                                                                                                                                                                                                                +
       SUM(ap.gross_amount) as debits_total                                                                                                                                                                                                                 +
     FROM artist_payments ap                                                                                                                                                                                                                                +
     WHERE ap.status IN ('completed', 'paid')                                                                                                                                                                                                               +
     GROUP BY ap.artist_profile_id                                                                                                                                                                                                                          +
   ),                                                                                                                                                                                                                                                       +
   recent_event_info AS (                                                                                                                                                                                                                                   +
     SELECT                                                                                                                                                                                                                                                 +
       rc.artist_id,                                                                                                                                                                                                                                        +
       c.name as event_city,                                                                                                                                                                                                                                +
       COUNT(DISTINCT e.id) as contest_count,                                                                                                                                                                                                               +
       ROW_NUMBER() OVER (PARTITION BY rc.artist_id ORDER BY MAX(e.event_start_datetime) DESC) as rn                                                                                                                                                        +
     FROM round_contestants rc                                                                                                                                                                                                                              +
     JOIN rounds r ON rc.round_id = r.id                                                                                                                                                                                                                    +
     JOIN events e ON r.event_id = e.id                                                                                                                                                                                                                     +
     LEFT JOIN cities c ON e.city_id = c.id                                                                                                                                                                                                                 +
     WHERE e.event_start_datetime >= NOW() - INTERVAL '90 days'                                                                                                                                                                                             +
     GROUP BY rc.artist_id, c.name                                                                                                                                                                                                                          +
   )                                                                                                                                                                                                                                                        +
   SELECT                                                                                                                                                                                                                                                   +
     ap.id as artist_id,                                                                                                                                                                                                                                    +
     ap.name as artist_name,                                                                                                                                                                                                                                +
     ap.email as artist_email,                                                                                                                                                                                                                              +
     ap.phone as artist_phone,                                                                                                                                                                                                                              +
     ap.entry_id as artist_entry_id,                                                                                                                                                                                                                        +
     ap.country as artist_country,                                                                                                                                                                                                                          +
     GREATEST(0, COALESCE(asales.sales_total, 0) - COALESCE(pd.debits_total, 0)) as estimated_balance,                                                                                                                                                      +
     agp.stripe_recipient_id,                                                                                                                                                                                                                               +
     COALESCE(rei.event_city, 'No recent events') as recent_city,                                                                                                                                                                                           +
     COALESCE(rei.contest_count, 0) as recent_contests,                                                                                                                                                                                                     +
     COALESCE(agp.default_currency, 'USD') as default_currency                                                                                                                                                                                              +
   FROM artist_profiles ap                                                                                                                                                                                                                                  +
   LEFT JOIN art_sales asales ON ap.id = asales.artist_id                                                                                                                                                                                                   +
   LEFT JOIN payment_debits pd ON ap.id = pd.artist_profile_id                                                                                                                                                                                              +
   LEFT JOIN recent_event_info rei ON ap.id = rei.artist_id AND rei.rn = 1                                                                                                                                                                                  +
   JOIN artist_global_payments agp ON ap.id = agp.artist_profile_id                                                                                                                                                                                         +
   WHERE GREATEST(0, COALESCE(asales.sales_total, 0) - COALESCE(pd.debits_total, 0)) > 0.01                                                                                                                                                                 +
     AND agp.status = 'ready'                                                                                                                                                                                                                               +
     AND agp.stripe_recipient_id IS NOT NULL                                                                                                                                                                                                                +
     AND LENGTH(agp.stripe_recipient_id) > 0                                                                                                                                                                                                                +
   ORDER BY estimated_balance DESC;                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                 +
 
(1 row)

