                                                                                                                                                                  pg_get_functiondef                                                                                                                                                                   
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_artist_invitation_history(p_artist_profile_id uuid)                                                                                                                                                                                                                                                            +
  RETURNS TABLE(id uuid, invitation_method character varying, recipient_email character varying, recipient_phone character varying, sent_by character varying, sent_at timestamp with time zone, status character varying, invitation_type character varying, message_content text, delivery_metadata jsonb, error_message text, time_since_sent text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                    +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                    +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                                                                                                                                                        +
 BEGIN                                                                                                                                                                                                                                                                                                                                                +
     RETURN QUERY                                                                                                                                                                                                                                                                                                                                     +
     SELECT                                                                                                                                                                                                                                                                                                                                           +
         psi.id,                                                                                                                                                                                                                                                                                                                                      +
         psi.invitation_method,                                                                                                                                                                                                                                                                                                                       +
         psi.recipient_email,                                                                                                                                                                                                                                                                                                                         +
         psi.recipient_phone,                                                                                                                                                                                                                                                                                                                         +
         psi.sent_by,                                                                                                                                                                                                                                                                                                                                 +
         psi.sent_at,                                                                                                                                                                                                                                                                                                                                 +
         psi.status,                                                                                                                                                                                                                                                                                                                                  +
         psi.invitation_type,                                                                                                                                                                                                                                                                                                                         +
         psi.message_content,                                                                                                                                                                                                                                                                                                                         +
         psi.delivery_metadata,                                                                                                                                                                                                                                                                                                                       +
         psi.error_message,                                                                                                                                                                                                                                                                                                                           +
         CASE                                                                                                                                                                                                                                                                                                                                         +
             WHEN AGE(NOW(), psi.sent_at) < INTERVAL '1 hour' THEN                                                                                                                                                                                                                                                                                    +
                 EXTRACT(epoch FROM AGE(NOW(), psi.sent_at))::INTEGER / 60 || 'm ago'                                                                                                                                                                                                                                                                 +
             WHEN AGE(NOW(), psi.sent_at) < INTERVAL '1 day' THEN                                                                                                                                                                                                                                                                                     +
                 EXTRACT(epoch FROM AGE(NOW(), psi.sent_at))::INTEGER / 3600 || 'h ago'                                                                                                                                                                                                                                                               +
             WHEN AGE(NOW(), psi.sent_at) < INTERVAL '7 days' THEN                                                                                                                                                                                                                                                                                    +
                 EXTRACT(epoch FROM AGE(NOW(), psi.sent_at))::INTEGER / 86400 || 'd ago'                                                                                                                                                                                                                                                              +
             ELSE                                                                                                                                                                                                                                                                                                                                     +
                 TO_CHAR(psi.sent_at, 'MM/DD/YYYY')                                                                                                                                                                                                                                                                                                   +
         END as time_since_sent                                                                                                                                                                                                                                                                                                                       +
     FROM payment_setup_invitations psi                                                                                                                                                                                                                                                                                                               +
     WHERE psi.artist_profile_id = p_artist_profile_id                                                                                                                                                                                                                                                                                                +
     ORDER BY psi.sent_at DESC;                                                                                                                                                                                                                                                                                                                       +
 END;                                                                                                                                                                                                                                                                                                                                                 +
 $function$                                                                                                                                                                                                                                                                                                                                           +
 
(1 row)

