                                                                                                                                            pg_get_functiondef                                                                                                                                             
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_sms_audience_paginated(p_city_ids uuid[] DEFAULT NULL::uuid[], p_event_ids uuid[] DEFAULT NULL::uuid[], p_recent_message_hours integer DEFAULT 72, p_offset integer DEFAULT 0, p_limit integer DEFAULT 50000)                                                      +
  RETURNS TABLE(id uuid, first_name character varying, last_name character varying, phone character varying, message_blocked integer, has_rfm boolean, rfm_recency_score integer, rfm_frequency_score integer, rfm_monetary_score integer, rfm_calculated_at timestamp with time zone, total_count bigint)+
  LANGUAGE sql                                                                                                                                                                                                                                                                                            +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                        +
 AS $function$                                                                                                                                                                                                                                                                                            +
   WITH filtered_people AS (                                                                                                                                                                                                                                                                              +
     SELECT DISTINCT                                                                                                                                                                                                                                                                                      +
       p.id,                                                                                                                                                                                                                                                                                              +
       p.first_name,                                                                                                                                                                                                                                                                                      +
       p.last_name,                                                                                                                                                                                                                                                                                       +
       p.phone,                                                                                                                                                                                                                                                                                           +
       p.message_blocked                                                                                                                                                                                                                                                                                  +
     FROM people p                                                                                                                                                                                                                                                                                        +
     WHERE                                                                                                                                                                                                                                                                                                +
       CASE                                                                                                                                                                                                                                                                                               +
         -- If both city and event filters are provided                                                                                                                                                                                                                                                   +
         WHEN p_city_ids IS NOT NULL AND p_event_ids IS NOT NULL THEN                                                                                                                                                                                                                                     +
           p.id IN (                                                                                                                                                                                                                                                                                      +
             SELECT DISTINCT er.person_id                                                                                                                                                                                                                                                                 +
             FROM event_registrations er                                                                                                                                                                                                                                                                  +
             JOIN events e ON er.event_id = e.id                                                                                                                                                                                                                                                          +
             WHERE e.city_id = ANY(p_city_ids) AND e.id = ANY(p_event_ids)                                                                                                                                                                                                                                +
           )                                                                                                                                                                                                                                                                                              +
         -- If only city filter is provided                                                                                                                                                                                                                                                               +
         WHEN p_city_ids IS NOT NULL THEN                                                                                                                                                                                                                                                                 +
           p.id IN (                                                                                                                                                                                                                                                                                      +
             SELECT DISTINCT er.person_id                                                                                                                                                                                                                                                                 +
             FROM event_registrations er                                                                                                                                                                                                                                                                  +
             JOIN events e ON er.event_id = e.id                                                                                                                                                                                                                                                          +
             WHERE e.city_id = ANY(p_city_ids)                                                                                                                                                                                                                                                            +
           )                                                                                                                                                                                                                                                                                              +
         -- If only event filter is provided                                                                                                                                                                                                                                                              +
         WHEN p_event_ids IS NOT NULL THEN                                                                                                                                                                                                                                                                +
           p.id IN (                                                                                                                                                                                                                                                                                      +
             SELECT DISTINCT er.person_id                                                                                                                                                                                                                                                                 +
             FROM event_registrations er                                                                                                                                                                                                                                                                  +
             WHERE er.event_id = ANY(p_event_ids)                                                                                                                                                                                                                                                         +
           )                                                                                                                                                                                                                                                                                              +
         -- No filters - all people                                                                                                                                                                                                                                                                       +
         ELSE TRUE                                                                                                                                                                                                                                                                                        +
       END                                                                                                                                                                                                                                                                                                +
       -- Exclude people who got messages recently                                                                                                                                                                                                                                                        +
       AND (p.phone IS NULL OR p.phone NOT IN (                                                                                                                                                                                                                                                           +
         SELECT DISTINCT so.to_phone                                                                                                                                                                                                                                                                      +
         FROM sms_outbound so                                                                                                                                                                                                                                                                             +
         WHERE so.sent_at >= (NOW() - INTERVAL '1 hour' * p_recent_message_hours)                                                                                                                                                                                                                         +
         AND so.to_phone IS NOT NULL                                                                                                                                                                                                                                                                      +
       ))                                                                                                                                                                                                                                                                                                 +
   ),                                                                                                                                                                                                                                                                                                     +
   total_count_cte AS (                                                                                                                                                                                                                                                                                   +
     SELECT COUNT(*) as total_count FROM filtered_people                                                                                                                                                                                                                                                  +
   )                                                                                                                                                                                                                                                                                                      +
   SELECT                                                                                                                                                                                                                                                                                                 +
     fp.id,                                                                                                                                                                                                                                                                                               +
     fp.first_name,                                                                                                                                                                                                                                                                                       +
     fp.last_name,                                                                                                                                                                                                                                                                                        +
     fp.phone,                                                                                                                                                                                                                                                                                            +
     fp.message_blocked,                                                                                                                                                                                                                                                                                  +
     (rsc.person_id IS NOT NULL) as has_rfm,                                                                                                                                                                                                                                                              +
     rsc.recency_score as rfm_recency_score,                                                                                                                                                                                                                                                              +
     rsc.frequency_score as rfm_frequency_score,                                                                                                                                                                                                                                                          +
     rsc.monetary_score as rfm_monetary_score,                                                                                                                                                                                                                                                            +
     rsc.calculated_at as rfm_calculated_at,                                                                                                                                                                                                                                                              +
     tcc.total_count                                                                                                                                                                                                                                                                                      +
   FROM filtered_people fp                                                                                                                                                                                                                                                                                +
   CROSS JOIN total_count_cte tcc                                                                                                                                                                                                                                                                         +
   LEFT JOIN rfm_score_cache rsc ON fp.id = rsc.person_id                                                                                                                                                                                                                                                 +
     AND rsc.calculated_at >= (NOW() - INTERVAL '24 hours')                                                                                                                                                                                                                                               +
   ORDER BY fp.id                                                                                                                                                                                                                                                                                         +
   OFFSET p_offset                                                                                                                                                                                                                                                                                        +
   LIMIT p_limit;                                                                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                                                               +
 
(1 row)

