                                                                                                                                               pg_get_functiondef                                                                                                                                                
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_artists_owed()                                                                                                                                                                                                                                                           +
  RETURNS TABLE(artist_id uuid, artist_name text, artist_email text, artist_phone text, artist_entry_id integer, artist_country text, estimated_balance numeric, balance_currency text, stripe_recipient_id text, payment_account_status text, recent_city text, recent_contests integer, default_currency text)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                  +
 BEGIN                                                                                                                                                                                                                                                                                                          +
   RETURN QUERY                                                                                                                                                                                                                                                                                                 +
   WITH art_sales AS (                                                                                                                                                                                                                                                                                          +
     SELECT                                                                                                                                                                                                                                                                                                     +
       a.artist_id,                                                                                                                                                                                                                                                                                             +
       e.currency,                                                                                                                                                                                                                                                                                              +
       e.artist_auction_portion, -- Use dynamic percentage                                                                                                                                                                                                                                                      +
       SUM(COALESCE(a.final_price, a.current_bid, 0) * e.artist_auction_portion) as gross_earnings -- Dynamic calculation                                                                                                                                                                                       +
     FROM art a                                                                                                                                                                                                                                                                                                 +
     JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                         +
     WHERE a.status = 'paid'                                                                                                                                                                                                                                                                                    +
       AND COALESCE(a.final_price, a.current_bid, 0) > 0                                                                                                                                                                                                                                                        +
     GROUP BY a.artist_id, e.currency, e.artist_auction_portion                                                                                                                                                                                                                                                 +
   ),                                                                                                                                                                                                                                                                                                           +
   manual_payment_totals AS (                                                                                                                                                                                                                                                                                   +
     SELECT                                                                                                                                                                                                                                                                                                     +
       ap.artist_profile_id,                                                                                                                                                                                                                                                                                    +
       CASE                                                                                                                                                                                                                                                                                                     +
         WHEN ap.art_id IS NOT NULL THEN (                                                                                                                                                                                                                                                                      +
           SELECT e.currency                                                                                                                                                                                                                                                                                    +
           FROM art a                                                                                                                                                                                                                                                                                           +
           JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                   +
           WHERE a.id = ap.art_id                                                                                                                                                                                                                                                                               +
         )                                                                                                                                                                                                                                                                                                      +
         ELSE ap.currency                                                                                                                                                                                                                                                                                       +
       END as currency,                                                                                                                                                                                                                                                                                         +
       SUM(ap.gross_amount) as manual_debits_total                                                                                                                                                                                                                                                              +
     FROM artist_payments ap                                                                                                                                                                                                                                                                                    +
     WHERE ap.payment_type = 'manual'                                                                                                                                                                                                                                                                           +
       AND ap.status IN ('completed', 'paid', 'verified')                                                                                                                                                                                                                                                       +
     GROUP BY ap.artist_profile_id,                                                                                                                                                                                                                                                                             +
       CASE                                                                                                                                                                                                                                                                                                     +
         WHEN ap.art_id IS NOT NULL THEN (                                                                                                                                                                                                                                                                      +
           SELECT e.currency                                                                                                                                                                                                                                                                                    +
           FROM art a                                                                                                                                                                                                                                                                                           +
           JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                   +
           WHERE a.id = ap.art_id                                                                                                                                                                                                                                                                               +
         )                                                                                                                                                                                                                                                                                                      +
         ELSE ap.currency                                                                                                                                                                                                                                                                                       +
       END                                                                                                                                                                                                                                                                                                      +
   ),                                                                                                                                                                                                                                                                                                           +
   automated_payment_totals AS (                                                                                                                                                                                                                                                                                +
     SELECT                                                                                                                                                                                                                                                                                                     +
       ap.artist_profile_id,                                                                                                                                                                                                                                                                                    +
       CASE                                                                                                                                                                                                                                                                                                     +
         WHEN ap.art_id IS NOT NULL THEN (                                                                                                                                                                                                                                                                      +
           SELECT e.currency                                                                                                                                                                                                                                                                                    +
           FROM art a                                                                                                                                                                                                                                                                                           +
           JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                   +
           WHERE a.id = ap.art_id                                                                                                                                                                                                                                                                               +
         )                                                                                                                                                                                                                                                                                                      +
         ELSE ap.currency                                                                                                                                                                                                                                                                                       +
       END as currency,                                                                                                                                                                                                                                                                                         +
       SUM(ap.gross_amount) as automated_debits_total                                                                                                                                                                                                                                                           +
     FROM artist_payments ap                                                                                                                                                                                                                                                                                    +
     WHERE ap.payment_type = 'automated'                                                                                                                                                                                                                                                                        +
       AND ap.status IN ('completed', 'paid', 'verified')                                                                                                                                                                                                                                                       +
     GROUP BY ap.artist_profile_id,                                                                                                                                                                                                                                                                             +
       CASE                                                                                                                                                                                                                                                                                                     +
         WHEN ap.art_id IS NOT NULL THEN (                                                                                                                                                                                                                                                                      +
           SELECT e.currency                                                                                                                                                                                                                                                                                    +
           FROM art a                                                                                                                                                                                                                                                                                           +
           JOIN events e ON a.event_id = e.id                                                                                                                                                                                                                                                                   +
           WHERE a.id = ap.art_id                                                                                                                                                                                                                                                                               +
         )                                                                                                                                                                                                                                                                                                      +
         ELSE ap.currency                                                                                                                                                                                                                                                                                       +
       END                                                                                                                                                                                                                                                                                                      +
   ),                                                                                                                                                                                                                                                                                                           +
   artist_balances AS (                                                                                                                                                                                                                                                                                         +
     SELECT                                                                                                                                                                                                                                                                                                     +
       ars.artist_id,                                                                                                                                                                                                                                                                                           +
       ars.currency,                                                                                                                                                                                                                                                                                            +
       ars.gross_earnings,                                                                                                                                                                                                                                                                                      +
       COALESCE(mpt.manual_debits_total, 0) as manual_debits,                                                                                                                                                                                                                                                   +
       COALESCE(apt.automated_debits_total, 0) as automated_debits,                                                                                                                                                                                                                                             +
       (ars.gross_earnings - COALESCE(mpt.manual_debits_total, 0) - COALESCE(apt.automated_debits_total, 0)) as net_balance                                                                                                                                                                                     +
     FROM art_sales ars                                                                                                                                                                                                                                                                                         +
     LEFT JOIN manual_payment_totals mpt ON ars.artist_id = mpt.artist_profile_id AND ars.currency = mpt.currency                                                                                                                                                                                               +
     LEFT JOIN automated_payment_totals apt ON ars.artist_id = apt.artist_profile_id AND ars.currency = apt.currency                                                                                                                                                                                            +
     WHERE (ars.gross_earnings - COALESCE(mpt.manual_debits_total, 0) - COALESCE(apt.automated_debits_total, 0)) > 0.01                                                                                                                                                                                         +
   )                                                                                                                                                                                                                                                                                                            +
   SELECT                                                                                                                                                                                                                                                                                                       +
     ab.artist_id::UUID,                                                                                                                                                                                                                                                                                        +
     prof.name::TEXT,                                                                                                                                                                                                                                                                                           +
     prof.email::TEXT,                                                                                                                                                                                                                                                                                          +
     prof.phone::TEXT,                                                                                                                                                                                                                                                                                          +
     prof.entry_id::INTEGER,                                                                                                                                                                                                                                                                                    +
     prof.country::TEXT,                                                                                                                                                                                                                                                                                        +
     ab.net_balance::NUMERIC,                                                                                                                                                                                                                                                                                   +
     ab.currency::TEXT,                                                                                                                                                                                                                                                                                         +
     agp.stripe_recipient_id::TEXT,                                                                                                                                                                                                                                                                             +
     COALESCE(agp.status, 'not_set_up')::TEXT,                                                                                                                                                                                                                                                                  +
     ''::TEXT as recent_city,                                                                                                                                                                                                                                                                                   +
     0::INTEGER as recent_contests,                                                                                                                                                                                                                                                                             +
     COALESCE(agp.default_currency, 'USD')::TEXT                                                                                                                                                                                                                                                                +
   FROM artist_balances ab                                                                                                                                                                                                                                                                                      +
   JOIN artist_profiles prof ON ab.artist_id = prof.id                                                                                                                                                                                                                                                          +
   LEFT JOIN artist_global_payments agp ON prof.id = agp.artist_profile_id                                                                                                                                                                                                                                      +
   ORDER BY ab.net_balance DESC;                                                                                                                                                                                                                                                                                +
 END;                                                                                                                                                                                                                                                                                                           +
 $function$                                                                                                                                                                                                                                                                                                     +
 
(1 row)

