                                                                                                                                                                                                        pg_get_functiondef                                                                                                                                                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_artist_invitation_history(p_artist_profile_id uuid)                                                                                                                                                                                                                                                                                                                                        +
  RETURNS TABLE(id uuid, artist_profile_id uuid, invitation_method character varying, recipient_email character varying, recipient_phone character varying, sent_by character varying, sent_at timestamp with time zone, status character varying, invitation_type character varying, message_content text, delivery_metadata jsonb, error_message text, created_at timestamp with time zone, updated_at timestamp with time zone)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                    +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                            +
   RETURN QUERY                                                                                                                                                                                                                                                                                                                                                                                                                   +
   SELECT                                                                                                                                                                                                                                                                                                                                                                                                                         +
     pi.id,                                                                                                                                                                                                                                                                                                                                                                                                                       +
     pi.artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                        +
     pi.invite_type::VARCHAR as invitation_method,                                                                                                                                                                                                                                                                                                                                                                                +
     CASE                                                                                                                                                                                                                                                                                                                                                                                                                         +
       WHEN pi.invite_type = 'email' THEN (SELECT email FROM artist_profiles WHERE artist_profiles.id = pi.artist_profile_id)                                                                                                                                                                                                                                                                                                     +
       ELSE NULL                                                                                                                                                                                                                                                                                                                                                                                                                  +
     END::VARCHAR as recipient_email,                                                                                                                                                                                                                                                                                                                                                                                             +
     CASE                                                                                                                                                                                                                                                                                                                                                                                                                         +
       WHEN pi.invite_type = 'sms' THEN (SELECT phone FROM artist_profiles WHERE artist_profiles.id = pi.artist_profile_id)                                                                                                                                                                                                                                                                                                       +
       ELSE NULL                                                                                                                                                                                                                                                                                                                                                                                                                  +
     END::VARCHAR as recipient_phone,                                                                                                                                                                                                                                                                                                                                                                                             +
     COALESCE((SELECT email FROM auth.users WHERE auth.users.id = pi.sent_by_user_id), 'system')::VARCHAR as sent_by,                                                                                                                                                                                                                                                                                                             +
     pi.sent_at,                                                                                                                                                                                                                                                                                                                                                                                                                  +
     pi.status::VARCHAR,                                                                                                                                                                                                                                                                                                                                                                                                          +
     'payment_setup'::VARCHAR as invitation_type,                                                                                                                                                                                                                                                                                                                                                                                 +
     COALESCE(pi.email_body, pi.sms_message)::TEXT as message_content,                                                                                                                                                                                                                                                                                                                                                            +
     NULL::JSONB as delivery_metadata,                                                                                                                                                                                                                                                                                                                                                                                            +
     NULL::TEXT as error_message,                                                                                                                                                                                                                                                                                                                                                                                                 +
     pi.created_at,                                                                                                                                                                                                                                                                                                                                                                                                               +
     pi.updated_at                                                                                                                                                                                                                                                                                                                                                                                                                +
   FROM payment_invitations pi                                                                                                                                                                                                                                                                                                                                                                                                    +
   WHERE pi.artist_profile_id = p_artist_profile_id                                                                                                                                                                                                                                                                                                                                                                               +
   ORDER BY pi.sent_at DESC;                                                                                                                                                                                                                                                                                                                                                                                                      +
 END;                                                                                                                                                                                                                                                                                                                                                                                                                             +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                       +
 
(1 row)

