                                                                                                                                                                                                        pg_get_functiondef                                                                                                                                                                                                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.get_artist_invitation_history(p_artist_profile_id uuid)                                                                                                                                                                                                                                                                                                                                        +
  RETURNS TABLE(id uuid, artist_profile_id uuid, invitation_method character varying, recipient_email character varying, recipient_phone character varying, sent_by character varying, sent_at timestamp with time zone, status character varying, invitation_type character varying, message_content text, delivery_metadata jsonb, error_message text, created_at timestamp with time zone, updated_at timestamp with time zone)+
  LANGUAGE sql                                                                                                                                                                                                                                                                                                                                                                                                                    +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                                +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                                                                                                     +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                    +
   SELECT                                                                                                                                                                                                                                                                                                                                                                                                                         +
     id,                                                                                                                                                                                                                                                                                                                                                                                                                          +
     artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                           +
     invitation_method,                                                                                                                                                                                                                                                                                                                                                                                                           +
     recipient_email,                                                                                                                                                                                                                                                                                                                                                                                                             +
     recipient_phone,                                                                                                                                                                                                                                                                                                                                                                                                             +
     sent_by,                                                                                                                                                                                                                                                                                                                                                                                                                     +
     sent_at,                                                                                                                                                                                                                                                                                                                                                                                                                     +
     status,                                                                                                                                                                                                                                                                                                                                                                                                                      +
     invitation_type,                                                                                                                                                                                                                                                                                                                                                                                                             +
     message_content,                                                                                                                                                                                                                                                                                                                                                                                                             +
     delivery_metadata,                                                                                                                                                                                                                                                                                                                                                                                                           +
     error_message,                                                                                                                                                                                                                                                                                                                                                                                                               +
     created_at,                                                                                                                                                                                                                                                                                                                                                                                                                  +
     updated_at                                                                                                                                                                                                                                                                                                                                                                                                                   +
   FROM payment_setup_invitations                                                                                                                                                                                                                                                                                                                                                                                                 +
   WHERE artist_profile_id = p_artist_profile_id                                                                                                                                                                                                                                                                                                                                                                                  +
   ORDER BY sent_at DESC;                                                                                                                                                                                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                       +
 
(1 row)

