                                                                                                                                                                                                       pg_get_functiondef                                                                                                                                                                                                       
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.log_artist_auth(p_auth_user_id uuid, p_person_id uuid, p_phone text, p_event_type text, p_operation text, p_success boolean DEFAULT false, p_error_type text DEFAULT NULL::text, p_error_message text DEFAULT NULL::text, p_duration_ms integer DEFAULT NULL::integer, p_metadata jsonb DEFAULT NULL::jsonb)                                                                                +
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                             +
  SET search_path TO 'pg_catalog', 'public', 'auth', 'extensions'                                                                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                 +
  DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                      +
    log_id UUID;                                                                                                                                                                                                                                                                                                                                                                                                               +
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                        +
    INSERT INTO artist_auth_logs (                                                                                                                                                                                                                                                                                                                                                                                             +
      auth_user_id, person_id, phone, event_type, operation,                                                                                                                                                                                                                                                                                                                                                                   +
      success, error_type, error_message, duration_ms, metadata                                                                                                                                                                                                                                                                                                                                                                +
    ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                                 +
      p_auth_user_id, p_person_id, p_phone, p_event_type, p_operation,                                                                                                                                                                                                                                                                                                                                                         +
      p_success, p_error_type, p_error_message, p_duration_ms, p_metadata                                                                                                                                                                                                                                                                                                                                                      +
    ) RETURNING id INTO log_id;                                                                                                                                                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                                                                                                                                                                               +
    RETURN log_id;                                                                                                                                                                                                                                                                                                                                                                                                             +
  EXCEPTION                                                                                                                                                                                                                                                                                                                                                                                                                    +
    WHEN OTHERS THEN                                                                                                                                                                                                                                                                                                                                                                                                           +
      -- If logging fails, don't break the main operation                                                                                                                                                                                                                                                                                                                                                                      +
      RETURN NULL;                                                                                                                                                                                                                                                                                                                                                                                                             +
  END;                                                                                                                                                                                                                                                                                                                                                                                                                         +
  $function$                                                                                                                                                                                                                                                                                                                                                                                                                   +
 
 CREATE OR REPLACE FUNCTION public.log_artist_auth(p_event_type text, p_operation text, p_success boolean, p_error_type text DEFAULT NULL::text, p_error_message text DEFAULT NULL::text, p_duration_ms integer DEFAULT NULL::integer, p_phone text DEFAULT NULL::text, p_ip_address text DEFAULT NULL::text, p_user_agent text DEFAULT NULL::text, p_session_id text DEFAULT NULL::text, p_metadata jsonb DEFAULT NULL::jsonb)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                             +
  SET search_path TO 'pg_catalog', 'public', 'auth', 'extensions'                                                                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                 +
  DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                      +
      log_id uuid;                                                                                                                                                                                                                                                                                                                                                                                                             +
  BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                        +
      -- Insert with service role privileges                                                                                                                                                                                                                                                                                                                                                                                   +
      INSERT INTO artist_auth_logs (                                                                                                                                                                                                                                                                                                                                                                                           +
          event_type, operation, success, error_type, error_message,                                                                                                                                                                                                                                                                                                                                                           +
          duration_ms, phone, ip_address, user_agent, session_id, metadata,                                                                                                                                                                                                                                                                                                                                                    +
          auth_user_id, person_id                                                                                                                                                                                                                                                                                                                                                                                              +
      ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                               +
          p_event_type, p_operation, p_success, p_error_type, p_error_message,                                                                                                                                                                                                                                                                                                                                                 +
          p_duration_ms, p_phone, p_ip_address, p_user_agent, p_session_id, p_metadata,                                                                                                                                                                                                                                                                                                                                        +
          auth.uid(), auth.uid()                                                                                                                                                                                                                                                                                                                                                                                               +
      ) RETURNING id INTO log_id;                                                                                                                                                                                                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                                                                                                                                                                               +
      RETURN log_id;                                                                                                                                                                                                                                                                                                                                                                                                           +
  END;                                                                                                                                                                                                                                                                                                                                                                                                                         +
  $function$                                                                                                                                                                                                                                                                                                                                                                                                                   +
 
(2 rows)

