                                                                                                                                                                                                                                pg_get_functiondef                                                                                                                                                                                                                                
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.log_payment_setup_invitation(p_artist_profile_id uuid, p_invitation_method character varying, p_sent_by character varying, p_recipient_email character varying DEFAULT NULL::character varying, p_recipient_phone character varying DEFAULT NULL::character varying, p_invitation_type character varying DEFAULT 'payment_setup'::character varying, p_message_content text DEFAULT NULL::text, p_delivery_metadata jsonb DEFAULT '{}'::jsonb)+
  RETURNS uuid                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                                               +
  SECURITY DEFINER                                                                                                                                                                                                                                                                                                                                                                                                                                                               +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
 AS $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                   +
 DECLARE                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
     invitation_id UUID;                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
 BEGIN                                                                                                                                                                                                                                                                                                                                                                                                                                                                           +
     INSERT INTO payment_setup_invitations (                                                                                                                                                                                                                                                                                                                                                                                                                                     +
         artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         invitation_method,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         recipient_email,                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
         recipient_phone,                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
         sent_by,                                                                                                                                                                                                                                                                                                                                                                                                                                                                +
         invitation_type,                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
         message_content,                                                                                                                                                                                                                                                                                                                                                                                                                                                        +
         delivery_metadata,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         status                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
     ) VALUES (                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
         p_artist_profile_id,                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
         p_invitation_method,                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
         p_recipient_email,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         p_recipient_phone,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         p_sent_by,                                                                                                                                                                                                                                                                                                                                                                                                                                                              +
         p_invitation_type,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         p_message_content,                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
         p_delivery_metadata,                                                                                                                                                                                                                                                                                                                                                                                                                                                    +
         'sent'                                                                                                                                                                                                                                                                                                                                                                                                                                                                  +
     )                                                                                                                                                                                                                                                                                                                                                                                                                                                                           +
     RETURNING id INTO invitation_id;                                                                                                                                                                                                                                                                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +
     RETURN invitation_id;                                                                                                                                                                                                                                                                                                                                                                                                                                                       +
 END;                                                                                                                                                                                                                                                                                                                                                                                                                                                                            +
 $function$                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
 
(1 row)

