                                                                                                                                 pg_get_functiondef                                                                                                                                 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.log_sms_activity(p_message_type text, p_related_id uuid, p_phone_number text, p_action text, p_status text DEFAULT NULL::text, p_message text DEFAULT NULL::text, p_metadata jsonb DEFAULT '{}'::jsonb, p_error_details text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                                                     +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                 +
  SECURITY DEFINER                                                                                                                                                                                                                                                                 +
  SET search_path TO 'pg_catalog', 'public', 'auth', 'extensions'                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                                     +
  DECLARE                                                                                                                                                                                                                                                                          +
      log_id UUID;                                                                                                                                                                                                                                                                 +
  BEGIN                                                                                                                                                                                                                                                                            +
      INSERT INTO sms_logs (                                                                                                                                                                                                                                                       +
          message_type, related_id, phone_number, action,                                                                                                                                                                                                                          +
          status, message, metadata, error_details                                                                                                                                                                                                                                 +
      ) VALUES (                                                                                                                                                                                                                                                                   +
          p_message_type, p_related_id, p_phone_number, p_action,                                                                                                                                                                                                                  +
          p_status, p_message, p_metadata, p_error_details                                                                                                                                                                                                                         +
      ) RETURNING id INTO log_id;                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                   +
      RETURN log_id;                                                                                                                                                                                                                                                               +
  END;                                                                                                                                                                                                                                                                             +
  $function$                                                                                                                                                                                                                                                                       +
 
(1 row)

