                                                                                                                                                             pg_get_functiondef                                                                                                                                                             
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.lookup_profiles_by_contact(target_phone text, target_email text DEFAULT NULL::text)                                                                                                                                                                                                                     +
  RETURNS TABLE(id uuid, name character varying, email character varying, phone character varying, bio text, city character varying, website text, instagram character varying, facebook character varying, mongo_id character varying, person_id uuid, set_primary_profile_at timestamp without time zone, match_type text, score integer)+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                                                                                                                                             +
  BEGIN                                                                                                                                                                                                                                                                                                                                    +
      RETURN QUERY                                                                                                                                                                                                                                                                                                                         +
      WITH normalized_phone AS (                                                                                                                                                                                                                                                                                                           +
          SELECT CASE                                                                                                                                                                                                                                                                                                                      +
              WHEN target_phone LIKE '+%' THEN target_phone                                                                                                                                                                                                                                                                                +
              ELSE '+' || target_phone                                                                                                                                                                                                                                                                                                     +
          END as phone                                                                                                                                                                                                                                                                                                                     +
      ),                                                                                                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                                                                                                           +
      -- Phone matches (highest priority)                                                                                                                                                                                                                                                                                                  +
      phone_matches AS (                                                                                                                                                                                                                                                                                                                   +
          SELECT                                                                                                                                                                                                                                                                                                                           +
              ap.id,                                                                                                                                                                                                                                                                                                                       +
              ap.name,                                                                                                                                                                                                                                                                                                                     +
              ap.email,                                                                                                                                                                                                                                                                                                                    +
              ap.phone,                                                                                                                                                                                                                                                                                                                    +
              ap.bio,                                                                                                                                                                                                                                                                                                                      +
              ap.city,                                                                                                                                                                                                                                                                                                                     +
              ap.website,                                                                                                                                                                                                                                                                                                                  +
              ap.instagram,                                                                                                                                                                                                                                                                                                                +
              ap.facebook,                                                                                                                                                                                                                                                                                                                 +
              ap.mongo_id,                                                                                                                                                                                                                                                                                                                 +
              ap.person_id,                                                                                                                                                                                                                                                                                                                +
              ap.set_primary_profile_at,                                                                                                                                                                                                                                                                                                   +
              'phone'::TEXT as match_type,                                                                                                                                                                                                                                                                                                 +
              100 as score                                                                                                                                                                                                                                                                                                                 +
          FROM artist_profiles ap                                                                                                                                                                                                                                                                                                          +
          CROSS JOIN normalized_phone np                                                                                                                                                                                                                                                                                                   +
          WHERE ap.phone = np.phone                                                                                                                                                                                                                                                                                                        +
             OR ap.phone = REPLACE(np.phone, '+', '')                                                                                                                                                                                                                                                                                      +
             OR ('+' || ap.phone) = np.phone                                                                                                                                                                                                                                                                                               +
      ),                                                                                                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                                                                                                           +
      -- Email matches (if provided and no phone matches)                                                                                                                                                                                                                                                                                  +
      email_matches AS (                                                                                                                                                                                                                                                                                                                   +
          SELECT                                                                                                                                                                                                                                                                                                                           +
              ap.id,                                                                                                                                                                                                                                                                                                                       +
              ap.name,                                                                                                                                                                                                                                                                                                                     +
              ap.email,                                                                                                                                                                                                                                                                                                                    +
              ap.phone,                                                                                                                                                                                                                                                                                                                    +
              ap.bio,                                                                                                                                                                                                                                                                                                                      +
              ap.city,                                                                                                                                                                                                                                                                                                                     +
              ap.website,                                                                                                                                                                                                                                                                                                                  +
              ap.instagram,                                                                                                                                                                                                                                                                                                                +
              ap.facebook,                                                                                                                                                                                                                                                                                                                 +
              ap.mongo_id,                                                                                                                                                                                                                                                                                                                 +
              ap.person_id,                                                                                                                                                                                                                                                                                                                +
              ap.set_primary_profile_at,                                                                                                                                                                                                                                                                                                   +
              'email'::TEXT as match_type,                                                                                                                                                                                                                                                                                                 +
              80 as score                                                                                                                                                                                                                                                                                                                  +
          FROM artist_profiles ap                                                                                                                                                                                                                                                                                                          +
          WHERE target_email IS NOT NULL                                                                                                                                                                                                                                                                                                   +
            AND ap.email = target_email                                                                                                                                                                                                                                                                                                    +
            AND NOT EXISTS (SELECT 1 FROM phone_matches)                                                                                                                                                                                                                                                                                   +
      )                                                                                                                                                                                                                                                                                                                                    +
                                                                                                                                                                                                                                                                                                                                           +
      -- Return phone matches first, then email matches                                                                                                                                                                                                                                                                                    +
      SELECT * FROM phone_matches                                                                                                                                                                                                                                                                                                          +
      UNION ALL                                                                                                                                                                                                                                                                                                                            +
      SELECT * FROM email_matches                                                                                                                                                                                                                                                                                                          +
      ORDER BY score DESC, name;                                                                                                                                                                                                                                                                                                           +
  END;                                                                                                                                                                                                                                                                                                                                     +
  $function$                                                                                                                                                                                                                                                                                                                               +
 
(1 row)

