                                                                                                                                                       pg_get_functiondef                                                                                                                                                        
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.multi_profile_lookup(target_phone text)                                                                                                                                                                                                                                                      +
  RETURNS TABLE(id uuid, source_type text, display_name text, email text, phone text, bio text, city text, website text, instagram text, facebook text, mongo_id text, person_id uuid, existing_profile_id uuid, form_17_entry_id integer, form_17_metadata jsonb, recommended_action text, score integer, match_reasons text[])+
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                              +
 AS $function$                                                                                                                                                                                                                                                                                                                  +
  BEGIN                                                                                                                                                                                                                                                                                                                         +
      RETURN QUERY                                                                                                                                                                                                                                                                                                              +
      WITH normalized_phone AS (                                                                                                                                                                                                                                                                                                +
          SELECT CASE                                                                                                                                                                                                                                                                                                           +
              WHEN target_phone LIKE '+%' THEN target_phone                                                                                                                                                                                                                                                                     +
              ELSE '+' || target_phone                                                                                                                                                                                                                                                                                          +
          END as phone                                                                                                                                                                                                                                                                                                          +
      ),                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                +
      -- Source 1: Existing artist profiles with matching person phone                                                                                                                                                                                                                                                          +
      existing_profiles AS (                                                                                                                                                                                                                                                                                                    +
          SELECT                                                                                                                                                                                                                                                                                                                +
              ap.id,                                                                                                                                                                                                                                                                                                            +
              'existing_profile'::TEXT as source_type,                                                                                                                                                                                                                                                                          +
              COALESCE(ap.name, '') as display_name,                                                                                                                                                                                                                                                                            +
              COALESCE(ap.email, p.email, '') as email,                                                                                                                                                                                                                                                                         +
              COALESCE(ap.phone, p.phone, '') as phone,                                                                                                                                                                                                                                                                         +
              COALESCE(ap.bio, '') as bio,                                                                                                                                                                                                                                                                                      +
              COALESCE(ap.city, '') as city,                                                                                                                                                                                                                                                                                    +
              COALESCE(ap.website, '') as website,                                                                                                                                                                                                                                                                              +
              COALESCE(ap.instagram, '') as instagram,                                                                                                                                                                                                                                                                          +
              COALESCE(ap.facebook, '') as facebook,                                                                                                                                                                                                                                                                            +
              COALESCE(ap.mongo_id, '') as mongo_id,                                                                                                                                                                                                                                                                            +
              p.id as person_id,                                                                                                                                                                                                                                                                                                +
              ap.id as existing_profile_id,                                                                                                                                                                                                                                                                                     +
              ap.form_17_entry_id,                                                                                                                                                                                                                                                                                              +
              '{}'::jsonb as form_17_metadata,                                                                                                                                                                                                                                                                                  +
              'use_existing_profile'::TEXT as recommended_action,                                                                                                                                                                                                                                                               +
              100 as score,                                                                                                                                                                                                                                                                                                     +
              ARRAY['phone_match', 'existing_profile']::TEXT[] as match_reasons                                                                                                                                                                                                                                                 +
          FROM artist_profiles ap                                                                                                                                                                                                                                                                                               +
          JOIN people p ON ap.person_id = p.id                                                                                                                                                                                                                                                                                  +
          CROSS JOIN normalized_phone np                                                                                                                                                                                                                                                                                        +
          WHERE p.phone = np.phone                                                                                                                                                                                                                                                                                              +
      ),                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                +
      -- Source 2: People records without artist profiles                                                                                                                                                                                                                                                                       +
      people_without_profiles AS (                                                                                                                                                                                                                                                                                              +
          SELECT                                                                                                                                                                                                                                                                                                                +
              gen_random_uuid() as id,                                                                                                                                                                                                                                                                                          +
              'person_record'::TEXT as source_type,                                                                                                                                                                                                                                                                             +
              COALESCE(p.first_name || ' ' || p.last_name, p.email, 'Unknown') as display_name,                                                                                                                                                                                                                                 +
              COALESCE(p.email, '') as email,                                                                                                                                                                                                                                                                                   +
              COALESCE(p.phone, '') as phone,                                                                                                                                                                                                                                                                                   +
              ''::TEXT as bio,                                                                                                                                                                                                                                                                                                  +
              ''::TEXT as city,                                                                                                                                                                                                                                                                                                 +
              ''::TEXT as website,                                                                                                                                                                                                                                                                                              +
              ''::TEXT as instagram,                                                                                                                                                                                                                                                                                            +
              ''::TEXT as facebook,                                                                                                                                                                                                                                                                                             +
              ''::TEXT as mongo_id,                                                                                                                                                                                                                                                                                             +
              p.id as person_id,                                                                                                                                                                                                                                                                                                +
              NULL::UUID as existing_profile_id,                                                                                                                                                                                                                                                                                +
              NULL::INTEGER as form_17_entry_id,                                                                                                                                                                                                                                                                                +
              '{}'::jsonb as form_17_metadata,                                                                                                                                                                                                                                                                                  +
              'link_to_person'::TEXT as recommended_action,                                                                                                                                                                                                                                                                     +
              80 as score,                                                                                                                                                                                                                                                                                                      +
              ARRAY['phone_match', 'person_record']::TEXT[] as match_reasons                                                                                                                                                                                                                                                    +
          FROM people p                                                                                                                                                                                                                                                                                                         +
          CROSS JOIN normalized_phone np                                                                                                                                                                                                                                                                                        +
          WHERE p.phone = np.phone                                                                                                                                                                                                                                                                                              +
            AND NOT EXISTS (                                                                                                                                                                                                                                                                                                    +
                SELECT 1 FROM artist_profiles ap WHERE ap.person_id = p.id                                                                                                                                                                                                                                                      +
            )                                                                                                                                                                                                                                                                                                                   +
      ),                                                                                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                                                                                                +
      -- Source 3: Form 17 entries with matching phone (from artist_profile_aliases)                                                                                                                                                                                                                                            +
      form_17_candidates AS (                                                                                                                                                                                                                                                                                                   +
          SELECT                                                                                                                                                                                                                                                                                                                +
              gen_random_uuid() as id,                                                                                                                                                                                                                                                                                          +
              'form_17_entry'::TEXT as source_type,                                                                                                                                                                                                                                                                             +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'extracted_data'->>'first_name' || ' ' ||                                                                                                                                                                                                                                               +
                  apa.form_17_metadata->'extracted_data'->>'last_name',                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'1',                                                                                                                                                                                                                                                                 +
                  'Form 17 Entry'                                                                                                                                                                                                                                                                                               +
              ) as display_name,                                                                                                                                                                                                                                                                                                +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'extracted_data'->>'email',                                                                                                                                                                                                                                                             +
                  apa.form_17_metadata->'form_17_fields'->>'14',                                                                                                                                                                                                                                                                +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as email,                                                                                                                                                                                                                                                                                                       +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'extracted_data'->>'phone',                                                                                                                                                                                                                                                             +
                  apa.form_17_metadata->'form_17_fields'->>'3',                                                                                                                                                                                                                                                                 +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as phone,                                                                                                                                                                                                                                                                                                       +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'5',                                                                                                                                                                                                                                                                 +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as bio,                                                                                                                                                                                                                                                                                                         +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'93.3',                                                                                                                                                                                                                                                              +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as city,                                                                                                                                                                                                                                                                                                        +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'4',                                                                                                                                                                                                                                                                 +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as website,                                                                                                                                                                                                                                                                                                     +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'16',                                                                                                                                                                                                                                                                +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as instagram,                                                                                                                                                                                                                                                                                                   +
              COALESCE(                                                                                                                                                                                                                                                                                                         +
                  apa.form_17_metadata->'form_17_fields'->>'17',                                                                                                                                                                                                                                                                +
                  ''                                                                                                                                                                                                                                                                                                            +
              ) as facebook,                                                                                                                                                                                                                                                                                                    +
              ''::TEXT as mongo_id,                                                                                                                                                                                                                                                                                             +
              NULL::UUID as person_id,                                                                                                                                                                                                                                                                                          +
              NULL::UUID as existing_profile_id,                                                                                                                                                                                                                                                                                +
              apa.form_17_entry_id,                                                                                                                                                                                                                                                                                             +
              apa.form_17_metadata,                                                                                                                                                                                                                                                                                             +
              'create_new_profile'::TEXT as recommended_action,                                                                                                                                                                                                                                                                 +
              apa.score,                                                                                                                                                                                                                                                                                                        +
              ARRAY['form_17_match']::TEXT[] as match_reasons                                                                                                                                                                                                                                                                   +
          FROM artist_profile_aliases apa                                                                                                                                                                                                                                                                                       +
          CROSS JOIN normalized_phone np                                                                                                                                                                                                                                                                                        +
          WHERE (                                                                                                                                                                                                                                                                                                               +
              apa.form_17_metadata->'extracted_data'->>'phone' = np.phone OR                                                                                                                                                                                                                                                    +
              apa.form_17_metadata->'form_17_fields'->>'3' = np.phone OR                                                                                                                                                                                                                                                        +
              apa.form_17_metadata->'extracted_data'->>'phone' = REPLACE(np.phone, '+', '') OR                                                                                                                                                                                                                                  +
              apa.form_17_metadata->'form_17_fields'->>'3' = REPLACE(np.phone, '+', '')                                                                                                                                                                                                                                         +
          )                                                                                                                                                                                                                                                                                                                     +
          AND apa.score >= 70  -- Only include high-confidence matches                                                                                                                                                                                                                                                          +
          AND NOT EXISTS (                                                                                                                                                                                                                                                                                                      +
              SELECT 1 FROM artist_profiles ap WHERE ap.form_17_entry_id = apa.form_17_entry_id                                                                                                                                                                                                                                 +
          )                                                                                                                                                                                                                                                                                                                     +
      )                                                                                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                                                                +
      -- Combine all sources and order by score                                                                                                                                                                                                                                                                                 +
      SELECT * FROM existing_profiles                                                                                                                                                                                                                                                                                           +
      UNION ALL                                                                                                                                                                                                                                                                                                                 +
      SELECT * FROM people_without_profiles                                                                                                                                                                                                                                                                                     +
      UNION ALL                                                                                                                                                                                                                                                                                                                 +
      SELECT * FROM form_17_candidates                                                                                                                                                                                                                                                                                          +
      ORDER BY score DESC, source_type;                                                                                                                                                                                                                                                                                         +
  END;                                                                                                                                                                                                                                                                                                                          +
  $function$                                                                                                                                                                                                                                                                                                                    +
 
(1 row)

