                                                                                                                     pg_get_functiondef                                                                                                                      
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.notify_auth_webhook()                                                                                                                                                                                                    +
  RETURNS trigger                                                                                                                                                                                                                                           +
  LANGUAGE plpgsql                                                                                                                                                                                                                                          +
  SECURITY DEFINER                                                                                                                                                                                                                                          +
 AS $function$                                                                                                                                                                                                                                              +
 BEGIN                                                                                                                                                                                                                                                      +
   -- Only process when phone_confirmed_at changes from NULL to a timestamp                                                                                                                                                                                 +
   IF OLD.phone_confirmed_at IS NOT NULL OR NEW.phone_confirmed_at IS NULL THEN                                                                                                                                                                             +
     RETURN NEW;                                                                                                                                                                                                                                            +
   END IF;                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                            +
   -- Use pg_net to call our webhook with the correct service role token                                                                                                                                                                                    +
   PERFORM net.http_post(                                                                                                                                                                                                                                   +
     'https://xsqdkubgyqwpyvfltnrf.supabase.co/functions/v1/auth-webhook',                                                                                                                                                                                  +
     jsonb_build_object(                                                                                                                                                                                                                                    +
       'type', 'UPDATE',                                                                                                                                                                                                                                    +
       'table', 'users',                                                                                                                                                                                                                                    +
       'schema', 'auth',                                                                                                                                                                                                                                    +
       'record', to_jsonb(NEW),                                                                                                                                                                                                                             +
       'old_record', to_jsonb(OLD)                                                                                                                                                                                                                          +
     ),                                                                                                                                                                                                                                                     +
     '{}',                                                                                                                                                                                                                                                  +
     jsonb_build_object(                                                                                                                                                                                                                                    +
       'Content-Type', 'application/json',                                                                                                                                                                                                                  +
       'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzcWRrdWJneXF3cHl2Zmx0bnJmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1MzQyMTY5NiwiZXhwIjoyMDY4OTk3Njk2fQ.wQieprnqKOD1Ez-OJVzl9MbjvxmqNtW0FDzrkSPcDrg'+
     )                                                                                                                                                                                                                                                      +
   );                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                            +
   RETURN NEW;                                                                                                                                                                                                                                              +
 END;                                                                                                                                                                                                                                                       +
 $function$                                                                                                                                                                                                                                                 +
 
(1 row)

