                                                                                                               pg_get_functiondef                                                                                                               
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.queue_bid_confirmation(p_user_mongo_id text, p_person_id uuid, p_art_id text, p_artist_name text, p_amount numeric, p_currency_symbol text, p_user_data jsonb, p_event_phone_number text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                             +
 AS $function$                                                                                                                                                                                                                                 +
 DECLARE                                                                                                                                                                                                                                       +
   v_phone TEXT;                                                                                                                                                                                                                               +
   v_nickname TEXT;                                                                                                                                                                                                                            +
   v_hash TEXT;                                                                                                                                                                                                                                +
   v_vote_url TEXT;                                                                                                                                                                                                                            +
   v_message TEXT;                                                                                                                                                                                                                             +
   v_message_id UUID;                                                                                                                                                                                                                          +
   v_eid TEXT;                                                                                                                                                                                                                                 +
 BEGIN                                                                                                                                                                                                                                         +
   -- Extract user data                                                                                                                                                                                                                        +
   v_phone := p_user_data->>'PhoneNumber';                                                                                                                                                                                                     +
   v_nickname := p_user_data->>'NickName';                                                                                                                                                                                                     +
   v_hash := p_user_data->>'Hash';                                                                                                                                                                                                             +
                                                                                                                                                                                                                                               +
   IF v_phone IS NULL THEN                                                                                                                                                                                                                     +
     RETURN NULL;                                                                                                                                                                                                                              +
   END IF;                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                               +
   -- Extract EID from art_id (e.g., "AB2941-1-2" -> "AB2941")                                                                                                                                                                                 +
   v_eid := SPLIT_PART(p_art_id, '-', 1);                                                                                                                                                                                                      +
                                                                                                                                                                                                                                               +
   -- Construct URL to event page                                                                                                                                                                                                              +
   v_vote_url := format('https://artb.art/event/%s', v_eid);                                                                                                                                                                                   +
                                                                                                                                                                                                                                               +
   -- Format message                                                                                                                                                                                                                           +
   v_message := format('%s%s Bid recorded on %s by %s %s',                                                                                                                                                                                     +
     p_currency_symbol,                                                                                                                                                                                                                        +
     p_amount,                                                                                                                                                                                                                                 +
     p_art_id,                                                                                                                                                                                                                                 +
     v_nickname,                                                                                                                                                                                                                               +
     v_vote_url                                                                                                                                                                                                                                +
   );                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                               +
   -- Send instantly                                                                                                                                                                                                                           +
   v_message_id := send_sms_instantly(                                                                                                                                                                                                         +
     p_destination := v_phone,                                                                                                                                                                                                                 +
     p_message_body := v_message,                                                                                                                                                                                                              +
     p_metadata := jsonb_build_object(                                                                                                                                                                                                         +
       'type', 'bid_confirmation',                                                                                                                                                                                                             +
       'art_id', p_art_id,                                                                                                                                                                                                                     +
       'user_id', p_user_mongo_id,                                                                                                                                                                                                             +
       'amount', p_amount,                                                                                                                                                                                                                     +
       'nickname', v_nickname                                                                                                                                                                                                                  +
     ),                                                                                                                                                                                                                                        +
     p_from_phone := p_event_phone_number                                                                                                                                                                                                      +
   );                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                               +
   RETURN v_message_id;                                                                                                                                                                                                                        +
 END;                                                                                                                                                                                                                                          +
 $function$                                                                                                                                                                                                                                    +
 
(1 row)

