                                                                                                               pg_get_functiondef                                                                                                               
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.queue_bid_confirmation(p_user_mongo_id text, p_person_id uuid, p_art_id text, p_artist_name text, p_amount numeric, p_currency_symbol text, p_user_data jsonb, p_event_phone_number text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                             +
 AS $function$                                                                                                                                                                                                                                 +
 DECLARE                                                                                                                                                                                                                                       +
   v_phone TEXT;                                                                                                                                                                                                                               +
   v_nickname TEXT;                                                                                                                                                                                                                            +
   v_hash TEXT;                                                                                                                                                                                                                                +
   v_auction_url TEXT;                                                                                                                                                                                                                         +
   v_message TEXT;                                                                                                                                                                                                                             +
   v_message_id UUID;                                                                                                                                                                                                                          +
   v_event_id TEXT;                                                                                                                                                                                                                            +
   v_round_num TEXT;                                                                                                                                                                                                                           +
 BEGIN                                                                                                                                                                                                                                         +
   -- Extract user data                                                                                                                                                                                                                        +
   v_phone := p_user_data->>'PhoneNumber';                                                                                                                                                                                                     +
   v_nickname := p_user_data->>'NickName';                                                                                                                                                                                                     +
   v_hash := p_user_data->>'Hash';                                                                                                                                                                                                             +
                                                                                                                                                                                                                                               +
   RAISE NOTICE 'queue_bid_confirmation - Phone: %, Nickname: %', v_phone, v_nickname;                                                                                                                                                         +
                                                                                                                                                                                                                                               +
   IF v_phone IS NULL THEN                                                                                                                                                                                                                     +
     RAISE WARNING 'No phone number provided in user_data';                                                                                                                                                                                    +
     RETURN NULL;                                                                                                                                                                                                                              +
   END IF;                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                               +
   -- Extract event ID and round from art_code (e.g., "AB2900-1-1" -> "AB2900", "1")                                                                                                                                                           +
   v_event_id := split_part(p_art_id, '-', 1);                                                                                                                                                                                                 +
   v_round_num := split_part(p_art_id, '-', 2);                                                                                                                                                                                                +
                                                                                                                                                                                                                                               +
   -- Construct auction tab URL                                                                                                                                                                                                                +
   v_auction_url := format('%s/e/%s/auction',                                                                                                                                                                                                  +
     COALESCE(current_setting('app.site_url', true), 'https://artb.art'),                                                                                                                                                                      +
     v_event_id                                                                                                                                                                                                                                +
   );                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                               +
   -- Format improved message with round information                                                                                                                                                                                           +
   v_message := format('Your %s%s bid on %s''s Round %s artwork is confirmed!',                                                                                                                                                                +
     p_currency_symbol,                                                                                                                                                                                                                        +
     p_amount,                                                                                                                                                                                                                                 +
     p_artist_name,                                                                                                                                                                                                                            +
     v_round_num                                                                                                                                                                                                                               +
   );                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                               +
   RAISE NOTICE 'Sending SMS to % with message: %', v_phone, v_message;                                                                                                                                                                        +
                                                                                                                                                                                                                                               +
   -- Send instantly                                                                                                                                                                                                                           +
   v_message_id := send_sms_instantly(                                                                                                                                                                                                         +
     p_destination := v_phone,                                                                                                                                                                                                                 +
     p_message_body := v_message,                                                                                                                                                                                                              +
     p_metadata := jsonb_build_object(                                                                                                                                                                                                         +
       'type', 'bid_confirmation',                                                                                                                                                                                                             +
       'art_id', p_art_id,                                                                                                                                                                                                                     +
       'user_id', p_user_mongo_id,                                                                                                                                                                                                             +
       'amount', p_amount,                                                                                                                                                                                                                     +
       'nickname', v_nickname,                                                                                                                                                                                                                 +
       'event_id', v_event_id,                                                                                                                                                                                                                 +
       'message_version', 'improved_v1'                                                                                                                                                                                                        +
     )                                                                                                                                                                                                                                         +
   );                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                               +
   RAISE NOTICE 'SMS queued with ID: %', v_message_id;                                                                                                                                                                                         +
                                                                                                                                                                                                                                               +
   RETURN v_message_id;                                                                                                                                                                                                                        +
 END;                                                                                                                                                                                                                                          +
 $function$                                                                                                                                                                                                                                    +
 
(1 row)

