                                                                                                                      pg_get_functiondef                                                                                                                      
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.queue_outbid_notification(p_user_mongo_id text, p_person_id uuid, p_art_id text, p_artist_name text, p_amount numeric, p_currency_symbol text, p_outbidder_phone_last4 text)                                              +
  RETURNS void                                                                                                                                                                                                                                               +
  LANGUAGE plpgsql                                                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                                               +
  DECLARE                                                                                                                                                                                                                                                    +
    v_phone TEXT;                                                                                                                                                                                                                                            +
    v_vote_url TEXT;                                                                                                                                                                                                                                         +
    v_message TEXT;                                                                                                                                                                                                                                          +
    v_message_id UUID;                                                                                                                                                                                                                                       +
  BEGIN                                                                                                                                                                                                                                                      +
    -- Get user's phone number - check both phone columns                                                                                                                                                                                                    +
    SELECT COALESCE(phone_number, phone) INTO v_phone                                                                                                                                                                                                        +
    FROM people WHERE id = p_person_id;                                                                                                                                                                                                                      +
                                                                                                                                                                                                                                                             +
    IF v_phone IS NULL THEN                                                                                                                                                                                                                                  +
      RAISE WARNING 'No phone number found for person_id: %', p_person_id;                                                                                                                                                                                   +
      RETURN;                                                                                                                                                                                                                                                +
    END IF;                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                             +
    -- Extract event code from art_id (e.g., AB2900 from AB2900-1-5)                                                                                                                                                                                         +
    -- Construct auction URL format: https://artb.art/e/AB2900/auction                                                                                                                                                                                       +
    v_vote_url := format('%s/e/%s/auction',                                                                                                                                                                                                                  +
      COALESCE(current_setting('app.site_url', true), 'https://artb.art'),                                                                                                                                                                                   +
      split_part(p_art_id, '-', 1)                                                                                                                                                                                                                           +
    );                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                             +
    -- Format message with current bid amount and rebid URL                                                                                                                                                                                                  +
    v_message := format('OUTBID on %s-%s by %s - bid is at %s%s, rebid @ %s',                                                                                                                                                                                +
      p_art_id,                                                                                                                                                                                                                                              +
      p_artist_name,                                                                                                                                                                                                                                         +
      right(p_outbidder_phone_last4, 4),                                                                                                                                                                                                                     +
      p_currency_symbol,                                                                                                                                                                                                                                     +
      p_amount,                                                                                                                                                                                                                                              +
      v_vote_url                                                                                                                                                                                                                                             +
    );                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                             +
    -- Use send_sms_instantly to get correct from_phone                                                                                                                                                                                                      +
    v_message_id := send_sms_instantly(                                                                                                                                                                                                                      +
      p_destination := v_phone,                                                                                                                                                                                                                              +
      p_message_body := v_message,                                                                                                                                                                                                                           +
      p_metadata := jsonb_build_object(                                                                                                                                                                                                                      +
        'type', 'outbid_notification',                                                                                                                                                                                                                       +
        'art_id', p_art_id,                                                                                                                                                                                                                                  +
        'user_id', p_user_mongo_id,                                                                                                                                                                                                                          +
        'amount', p_amount                                                                                                                                                                                                                                   +
      )                                                                                                                                                                                                                                                      +
    );                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                             +
    RAISE NOTICE 'Outbid notification sent to % with message ID %', v_phone, v_message_id;                                                                                                                                                                   +
  END;                                                                                                                                                                                                                                                       +
  $function$                                                                                                                                                                                                                                                 +
 
 CREATE OR REPLACE FUNCTION public.queue_outbid_notification(p_user_mongo_id text, p_person_id uuid, p_art_id text, p_artist_name text, p_amount numeric, p_currency_symbol text, p_outbidder_phone_last4 text, p_event_phone_number text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                               +
  LANGUAGE plpgsql                                                                                                                                                                                                                                           +
 AS $function$                                                                                                                                                                                                                                               +
 DECLARE                                                                                                                                                                                                                                                     +
   v_phone TEXT;                                                                                                                                                                                                                                             +
   v_vote_url TEXT;                                                                                                                                                                                                                                          +
   v_message TEXT;                                                                                                                                                                                                                                           +
   v_message_id UUID;                                                                                                                                                                                                                                        +
 BEGIN                                                                                                                                                                                                                                                       +
   -- Get user's phone number                                                                                                                                                                                                                                +
   SELECT phone_number INTO v_phone                                                                                                                                                                                                                          +
   FROM people WHERE id = p_person_id;                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                             +
   IF v_phone IS NULL THEN                                                                                                                                                                                                                                   +
     RETURN NULL;                                                                                                                                                                                                                                            +
   END IF;                                                                                                                                                                                                                                                   +
                                                                                                                                                                                                                                                             +
   -- Construct URL                                                                                                                                                                                                                                          +
   v_vote_url := format('%s/a/%s',                                                                                                                                                                                                                           +
     COALESCE(current_setting('app.site_url', true), 'https://artb.art'),                                                                                                                                                                                    +
     p_art_id                                                                                                                                                                                                                                                +
   );                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                             +
   -- Format message                                                                                                                                                                                                                                         +
   v_message := format('OUTBID on %s by %s %s',                                                                                                                                                                                                              +
     p_art_id || '-' || p_artist_name,                                                                                                                                                                                                                       +
     p_outbidder_phone_last4,                                                                                                                                                                                                                                +
     v_vote_url                                                                                                                                                                                                                                              +
   );                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                             +
   -- Send instantly                                                                                                                                                                                                                                         +
   v_message_id := send_sms_instantly(                                                                                                                                                                                                                       +
     p_destination := v_phone,                                                                                                                                                                                                                               +
     p_message_body := v_message,                                                                                                                                                                                                                            +
     p_metadata := jsonb_build_object(                                                                                                                                                                                                                       +
       'type', 'outbid_notification',                                                                                                                                                                                                                        +
       'art_id', p_art_id,                                                                                                                                                                                                                                   +
       'user_id', p_user_mongo_id,                                                                                                                                                                                                                           +
       'amount', p_amount                                                                                                                                                                                                                                    +
     ),                                                                                                                                                                                                                                                      +
     p_from_phone := p_event_phone_number                                                                                                                                                                                                                    +
   );                                                                                                                                                                                                                                                        +
                                                                                                                                                                                                                                                             +
   RETURN v_message_id;                                                                                                                                                                                                                                      +
 END;                                                                                                                                                                                                                                                        +
 $function$                                                                                                                                                                                                                                                  +
 
(2 rows)

