                                                                                                                                      pg_get_functiondef                                                                                                                                       
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.secure_function_wrapper(function_name text, required_role text DEFAULT 'authenticated'::text, requires_admin boolean DEFAULT false, requires_super_admin boolean DEFAULT false, rate_limit_calls integer DEFAULT 100, rate_limit_window integer DEFAULT 60)+
  RETURNS boolean                                                                                                                                                                                                                                                                             +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                            +
  SET search_path TO 'public'                                                                                                                                                                                                                                                                 +
 AS $function$                                                                                                                                                                                                                                                                                +
 BEGIN                                                                                                                                                                                                                                                                                        +
     -- 1. Check authentication level                                                                                                                                                                                                                                                         +
     IF required_role = 'authenticated' AND auth.uid() IS NULL THEN                                                                                                                                                                                                                           +
         RAISE EXCEPTION 'Authentication required for function %', function_name;                                                                                                                                                                                                             +
     END IF;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                              +
     -- 2. Check admin privileges                                                                                                                                                                                                                                                             +
     IF requires_admin AND NOT is_admin() THEN                                                                                                                                                                                                                                                +
         RAISE EXCEPTION 'Admin privileges required for function %', function_name;                                                                                                                                                                                                           +
     END IF;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                              +
     -- 3. Check super admin privileges                                                                                                                                                                                                                                                       +
     IF requires_super_admin AND NOT is_super_admin() THEN                                                                                                                                                                                                                                    +
         RAISE EXCEPTION 'Super admin privileges required for function %', function_name;                                                                                                                                                                                                     +
     END IF;                                                                                                                                                                                                                                                                                  +
                                                                                                                                                                                                                                                                                              +
     -- 4. Check rate limits                                                                                                                                                                                                                                                                  +
     PERFORM check_rate_limit(function_name, rate_limit_calls, rate_limit_window);                                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                                              +
     -- 5. Log the function call for security monitoring                                                                                                                                                                                                                                      +
     PERFORM log_security_event(                                                                                                                                                                                                                                                              +
         function_name,                                                                                                                                                                                                                                                                       +
         'FUNCTION_CALL',                                                                                                                                                                                                                                                                     +
         auth.uid(),                                                                                                                                                                                                                                                                          +
         null,                                                                                                                                                                                                                                                                                +
         jsonb_build_object(                                                                                                                                                                                                                                                                  +
             'function', function_name,                                                                                                                                                                                                                                                       +
             'user_role', CASE WHEN is_super_admin() THEN 'super_admin'                                                                                                                                                                                                                       +
                              WHEN is_admin() THEN 'admin'                                                                                                                                                                                                                                    +
                              ELSE 'user' END                                                                                                                                                                                                                                                 +
         )                                                                                                                                                                                                                                                                                    +
     );                                                                                                                                                                                                                                                                                       +
                                                                                                                                                                                                                                                                                              +
     RETURN true;                                                                                                                                                                                                                                                                             +
 END;                                                                                                                                                                                                                                                                                         +
 $function$                                                                                                                                                                                                                                                                                   +
 
(1 row)

