                                                                                                                         pg_get_functiondef                                                                                                                          
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.send_payment_setup_invitation(artist_id uuid, invite_type text DEFAULT 'email'::text, custom_message text DEFAULT NULL::text, admin_note text DEFAULT NULL::text)                                                                +
  RETURNS json                                                                                                                                                                                                                                                      +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                  +
 AS $function$                                                                                                                                                                                                                                                      +
 DECLARE                                                                                                                                                                                                                                                            +
   artist_record artist_profiles%ROWTYPE;                                                                                                                                                                                                                           +
   invitation_id uuid;                                                                                                                                                                                                                                              +
   invite_token text;                                                                                                                                                                                                                                               +
   setup_url text := 'https://artb.art/profile';                                                                                                                                                                                                                    +
   email_content text;                                                                                                                                                                                                                                              +
   sms_content text;                                                                                                                                                                                                                                                +
 BEGIN                                                                                                                                                                                                                                                              +
   -- Get artist details                                                                                                                                                                                                                                            +
   SELECT * INTO artist_record FROM artist_profiles WHERE id = artist_id;                                                                                                                                                                                           +
                                                                                                                                                                                                                                                                    +
   IF NOT FOUND THEN                                                                                                                                                                                                                                                +
     RETURN json_build_object(                                                                                                                                                                                                                                      +
       'success', false,                                                                                                                                                                                                                                            +
       'error', 'Artist not found'                                                                                                                                                                                                                                  +
     );                                                                                                                                                                                                                                                             +
   END IF;                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                    +
   -- Generate unique invitation token                                                                                                                                                                                                                              +
   invite_token := encode(gen_random_bytes(32), 'hex');                                                                                                                                                                                                             +
                                                                                                                                                                                                                                                                    +
   -- Build email content with actual URL                                                                                                                                                                                                                           +
   IF invite_type = 'email' THEN                                                                                                                                                                                                                                    +
     email_content := CASE                                                                                                                                                                                                                                          +
       WHEN admin_note IS NOT NULL AND admin_note != '' THEN                                                                                                                                                                                                        +
         E'**IMPORTANT: ' || admin_note || E'**\n\n'                                                                                                                                                                                                                +
       ELSE ''                                                                                                                                                                                                                                                      +
     END || COALESCE(                                                                                                                                                                                                                                               +
       custom_message,                                                                                                                                                                                                                                              +
       'Hi ' || artist_record.name || E',\n\nYou have earnings from Art Battle events that are ready to be paid out. Please set up your payment account to receive your funds.\n\nClick here to get started: ' || setup_url || E'\n\nBest regards,\nArt Battle Team'+
     );                                                                                                                                                                                                                                                             +
   END IF;                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                    +
   -- Build SMS content with actual URL                                                                                                                                                                                                                             +
   IF invite_type = 'sms' THEN                                                                                                                                                                                                                                      +
     sms_content := CASE                                                                                                                                                                                                                                            +
       WHEN admin_note IS NOT NULL AND admin_note != '' THEN                                                                                                                                                                                                        +
         E'**IMPORTANT: ' || admin_note || E'** '                                                                                                                                                                                                                   +
       ELSE ''                                                                                                                                                                                                                                                      +
     END || COALESCE(                                                                                                                                                                                                                                               +
       custom_message,                                                                                                                                                                                                                                              +
       'Hi ' || artist_record.name || '! You have Art Battle earnings ready. Set up payment: ' || setup_url                                                                                                                                                         +
     );                                                                                                                                                                                                                                                             +
   END IF;                                                                                                                                                                                                                                                          +
                                                                                                                                                                                                                                                                    +
   -- Create invitation record only (edge function will send email)                                                                                                                                                                                                 +
   INSERT INTO payment_invitations (                                                                                                                                                                                                                                +
     artist_profile_id,                                                                                                                                                                                                                                             +
     invite_type,                                                                                                                                                                                                                                                   +
     invitation_token,                                                                                                                                                                                                                                              +
     email_subject,                                                                                                                                                                                                                                                 +
     email_body,                                                                                                                                                                                                                                                    +
     sms_message                                                                                                                                                                                                                                                    +
   ) VALUES (                                                                                                                                                                                                                                                       +
     artist_id,                                                                                                                                                                                                                                                     +
     invite_type,                                                                                                                                                                                                                                                   +
     invite_token,                                                                                                                                                                                                                                                  +
     CASE WHEN invite_type = 'email' THEN 'Set up your Art Battle payment account' ELSE NULL END,                                                                                                                                                                   +
     CASE WHEN invite_type = 'email' THEN email_content ELSE NULL END,                                                                                                                                                                                              +
     CASE WHEN invite_type = 'sms' THEN sms_content ELSE NULL END                                                                                                                                                                                                   +
   ) RETURNING id INTO invitation_id;                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                                                    +
   -- Return success with email content for edge function to send                                                                                                                                                                                                   +
   RETURN json_build_object(                                                                                                                                                                                                                                        +
     'success', true,                                                                                                                                                                                                                                               +
     'invitation_id', invitation_id,                                                                                                                                                                                                                                +
     'artist_name', artist_record.name,                                                                                                                                                                                                                             +
     'artist_email', artist_record.email,                                                                                                                                                                                                                           +
     'artist_phone', artist_record.phone,                                                                                                                                                                                                                           +
     'invite_type', invite_type,                                                                                                                                                                                                                                    +
     'token', invite_token,                                                                                                                                                                                                                                         +
     'email_subject', CASE WHEN invite_type = 'email' THEN 'Set up your Art Battle payment account' ELSE NULL END,                                                                                                                                                  +
     'email_content', email_content,                                                                                                                                                                                                                                +
     'sms_content', sms_content,                                                                                                                                                                                                                                    +
     'message', 'Invitation created successfully'                                                                                                                                                                                                                   +
   );                                                                                                                                                                                                                                                               +
                                                                                                                                                                                                                                                                    +
 EXCEPTION WHEN OTHERS THEN                                                                                                                                                                                                                                         +
   RETURN json_build_object(                                                                                                                                                                                                                                        +
     'success', false,                                                                                                                                                                                                                                              +
     'error', 'Failed to create invitation: ' || SQLERRM                                                                                                                                                                                                            +
   );                                                                                                                                                                                                                                                               +
 END;                                                                                                                                                                                                                                                               +
 $function$                                                                                                                                                                                                                                                         +
 
(1 row)

