                                                                                                     pg_get_functiondef                                                                                                     
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.send_test_slack_notification(p_message_type character varying DEFAULT 'test'::character varying, p_message text DEFAULT 'This is a test notification from Art Battle Vote system'::text)+
  RETURNS jsonb                                                                                                                                                                                                            +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
 AS $function$                                                                                                                                                                                                             +
 DECLARE                                                                                                                                                                                                                   +
   v_event_id UUID;                                                                                                                                                                                                        +
   v_channel_id VARCHAR;                                                                                                                                                                                                   +
   v_notification_id UUID;                                                                                                                                                                                                 +
 BEGIN                                                                                                                                                                                                                     +
   -- Get test event                                                                                                                                                                                                       +
   SELECT e.id, es.channel_id                                                                                                                                                                                              +
   INTO v_event_id, v_channel_id                                                                                                                                                                                           +
   FROM events e                                                                                                                                                                                                           +
   JOIN event_slack_settings es ON es.event_id = e.id                                                                                                                                                                      +
   WHERE e.eid = 'TEST123';                                                                                                                                                                                                +
                                                                                                                                                                                                                           +
   IF v_channel_id IS NULL THEN                                                                                                                                                                                            +
     RETURN jsonb_build_object(                                                                                                                                                                                            +
       'success', false,                                                                                                                                                                                                   +
       'error', 'No Slack channel configured for test event'                                                                                                                                                               +
     );                                                                                                                                                                                                                    +
   END IF;                                                                                                                                                                                                                 +
                                                                                                                                                                                                                           +
   -- Queue test notification (without double escaping)                                                                                                                                                                    +
   INSERT INTO slack_notifications (                                                                                                                                                                                       +
     event_id,                                                                                                                                                                                                             +
     channel_id,                                                                                                                                                                                                           +
     message_type,                                                                                                                                                                                                         +
     payload                                                                                                                                                                                                               +
   ) VALUES (                                                                                                                                                                                                              +
     v_event_id,                                                                                                                                                                                                           +
     v_channel_id,                                                                                                                                                                                                         +
     p_message_type,                                                                                                                                                                                                       +
     jsonb_build_object(                                                                                                                                                                                                   +
       'message', p_message,                                                                                                                                                                                               +
       'test', true,                                                                                                                                                                                                       +
       'timestamp', NOW()                                                                                                                                                                                                  +
     )                                                                                                                                                                                                                     +
   ) RETURNING id INTO v_notification_id;                                                                                                                                                                                  +
                                                                                                                                                                                                                           +
   -- Process immediately                                                                                                                                                                                                  +
   PERFORM process_slack_notification(v_notification_id);                                                                                                                                                                  +
                                                                                                                                                                                                                           +
   -- Return result                                                                                                                                                                                                        +
   RETURN jsonb_build_object(                                                                                                                                                                                              +
     'success', true,                                                                                                                                                                                                      +
     'notification_id', v_notification_id,                                                                                                                                                                                 +
     'channel_id', v_channel_id,                                                                                                                                                                                           +
     'message', p_message                                                                                                                                                                                                  +
   );                                                                                                                                                                                                                      +
 END;                                                                                                                                                                                                                      +
 $function$                                                                                                                                                                                                                +
 
(1 row)

