                                                                                                                                                                                                                                                                                                                           pg_get_functiondef                                                                                                                                                                                                                                                                                                                            
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.send_slack_notification_batch()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
  RETURNS jsonb                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      +
 AS $function$ DECLARE v_notifications JSONB; v_count INT := 0; BEGIN WITH pending_notifications AS ( SELECT jsonb_build_object( 'id', id, 'channel', channel_id, 'text', payload->>'formatted_text', 'blocks', payload->'formatted_blocks' ) as notif FROM slack_notifications WHERE status = 'pending' AND attempts < 3 AND payload ? 'formatted_blocks' AND (last_attempt_at IS NULL OR last_attempt_at < NOW() - INTERVAL '1 minute') LIMIT 10 ) SELECT jsonb_agg(notif), COUNT(*) INTO v_notifications, v_count FROM pending_notifications; RETURN jsonb_build_object( 'notifications', COALESCE(v_notifications, '[]'::jsonb), 'count', v_count ); END; $function$+
 
(1 row)

