                                                                                                                          pg_get_functiondef                                                                                                                          
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.send_payment_setup_invitation(artist_id uuid, invite_type text DEFAULT 'email'::text, custom_message text DEFAULT NULL::text)                                                                                                     +
  RETURNS json                                                                                                                                                                                                                                                       +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                   +
  SECURITY DEFINER                                                                                                                                                                                                                                                   +
  SET search_path TO 'public'                                                                                                                                                                                                                                        +
 AS $function$                                                                                                                                                                                                                                                       +
 DECLARE                                                                                                                                                                                                                                                             +
   artist_record artist_profiles%ROWTYPE;                                                                                                                                                                                                                            +
   invitation_id uuid;                                                                                                                                                                                                                                               +
   invite_token text;                                                                                                                                                                                                                                                +
   result json;                                                                                                                                                                                                                                                      +
 BEGIN                                                                                                                                                                                                                                                               +
   -- Get artist details                                                                                                                                                                                                                                             +
   SELECT * INTO artist_record FROM artist_profiles WHERE id = artist_id;                                                                                                                                                                                            +
                                                                                                                                                                                                                                                                     +
   IF NOT FOUND THEN                                                                                                                                                                                                                                                 +
     RETURN json_build_object(                                                                                                                                                                                                                                       +
       'success', false,                                                                                                                                                                                                                                             +
       'error', 'Artist not found'                                                                                                                                                                                                                                   +
     );                                                                                                                                                                                                                                                              +
   END IF;                                                                                                                                                                                                                                                           +
                                                                                                                                                                                                                                                                     +
   -- Generate unique invitation token                                                                                                                                                                                                                               +
   invite_token := encode(gen_random_bytes(32), 'hex');                                                                                                                                                                                                              +
                                                                                                                                                                                                                                                                     +
   -- Create invitation record                                                                                                                                                                                                                                       +
   INSERT INTO payment_invitations (                                                                                                                                                                                                                                 +
     artist_profile_id,                                                                                                                                                                                                                                              +
     invite_type,                                                                                                                                                                                                                                                    +
     invitation_token,                                                                                                                                                                                                                                               +
     email_subject,                                                                                                                                                                                                                                                  +
     email_body,                                                                                                                                                                                                                                                     +
     sms_message                                                                                                                                                                                                                                                     +
   ) VALUES (                                                                                                                                                                                                                                                        +
     artist_id,                                                                                                                                                                                                                                                      +
     invite_type,                                                                                                                                                                                                                                                    +
     invite_token,                                                                                                                                                                                                                                                   +
     CASE                                                                                                                                                                                                                                                            +
       WHEN invite_type = 'email' THEN 'Set up your Art Battle payment account'                                                                                                                                                                                      +
       ELSE NULL                                                                                                                                                                                                                                                     +
     END,                                                                                                                                                                                                                                                            +
     CASE                                                                                                                                                                                                                                                            +
       WHEN invite_type = 'email' THEN COALESCE(                                                                                                                                                                                                                     +
         custom_message,                                                                                                                                                                                                                                             +
         'Hi ' || artist_record.name || ',\n\nYou have earnings from Art Battle events that are ready to be paid out. Please set up your payment account to receive your funds.\n\nClick here to get started: [PAYMENT_SETUP_LINK]\n\nBest regards,\nArt Battle Team'+
       )                                                                                                                                                                                                                                                             +
       ELSE NULL                                                                                                                                                                                                                                                     +
     END,                                                                                                                                                                                                                                                            +
     CASE                                                                                                                                                                                                                                                            +
       WHEN invite_type = 'sms' THEN COALESCE(                                                                                                                                                                                                                       +
         custom_message,                                                                                                                                                                                                                                             +
         'Hi ' || artist_record.name || '! You have Art Battle earnings ready. Set up payment: [PAYMENT_SETUP_LINK]'                                                                                                                                                 +
       )                                                                                                                                                                                                                                                             +
       ELSE NULL                                                                                                                                                                                                                                                     +
     END                                                                                                                                                                                                                                                             +
   ) RETURNING id INTO invitation_id;                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                     +
   -- Return success with invitation details                                                                                                                                                                                                                         +
   RETURN json_build_object(                                                                                                                                                                                                                                         +
     'success', true,                                                                                                                                                                                                                                                +
     'invitation_id', invitation_id,                                                                                                                                                                                                                                 +
     'artist_name', artist_record.name,                                                                                                                                                                                                                              +
     'artist_email', artist_record.email,                                                                                                                                                                                                                            +
     'artist_phone', artist_record.phone,                                                                                                                                                                                                                            +
     'invite_type', invite_type,                                                                                                                                                                                                                                     +
     'token', invite_token,                                                                                                                                                                                                                                          +
     'message', 'Invitation created successfully'                                                                                                                                                                                                                    +
   );                                                                                                                                                                                                                                                                +
                                                                                                                                                                                                                                                                     +
 EXCEPTION WHEN OTHERS THEN                                                                                                                                                                                                                                          +
   RETURN json_build_object(                                                                                                                                                                                                                                         +
     'success', false,                                                                                                                                                                                                                                               +
     'error', 'Failed to create invitation: ' || SQLERRM                                                                                                                                                                                                             +
   );                                                                                                                                                                                                                                                                +
 END;                                                                                                                                                                                                                                                                +
 $function$                                                                                                                                                                                                                                                          +
 
(1 row)

