                                                                                                                                       pg_get_functiondef                                                                                                                                       
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.track_sponsorship_interaction(p_invite_hash character varying, p_interaction_type character varying, p_package_id uuid DEFAULT NULL::uuid, p_metadata jsonb DEFAULT '{}'::jsonb, p_ip_address inet DEFAULT NULL::inet, p_user_agent text DEFAULT NULL::text)+
  RETURNS uuid                                                                                                                                                                                                                                                                                 +
  LANGUAGE plpgsql                                                                                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                                                                                             +
 AS $function$                                                                                                                                                                                                                                                                                 +
 DECLARE                                                                                                                                                                                                                                                                                       +
   v_invite_id UUID;                                                                                                                                                                                                                                                                           +
   v_event_id UUID;                                                                                                                                                                                                                                                                            +
   v_interaction_id UUID;                                                                                                                                                                                                                                                                      +
 BEGIN                                                                                                                                                                                                                                                                                         +
   -- Get invite and event IDs                                                                                                                                                                                                                                                                 +
   SELECT id, event_id INTO v_invite_id, v_event_id                                                                                                                                                                                                                                            +
   FROM sponsorship_invites                                                                                                                                                                                                                                                                    +
   WHERE hash = p_invite_hash;                                                                                                                                                                                                                                                                 +
                                                                                                                                                                                                                                                                                               +
   IF v_invite_id IS NULL THEN                                                                                                                                                                                                                                                                 +
     RAISE EXCEPTION 'Invalid invite hash';                                                                                                                                                                                                                                                    +
   END IF;                                                                                                                                                                                                                                                                                     +
                                                                                                                                                                                                                                                                                               +
   -- Insert interaction                                                                                                                                                                                                                                                                       +
   INSERT INTO sponsorship_interactions (                                                                                                                                                                                                                                                      +
     invite_id,                                                                                                                                                                                                                                                                                +
     event_id,                                                                                                                                                                                                                                                                                 +
     interaction_type,                                                                                                                                                                                                                                                                         +
     package_id,                                                                                                                                                                                                                                                                               +
     metadata,                                                                                                                                                                                                                                                                                 +
     ip_address,                                                                                                                                                                                                                                                                               +
     user_agent                                                                                                                                                                                                                                                                                +
   ) VALUES (                                                                                                                                                                                                                                                                                  +
     v_invite_id,                                                                                                                                                                                                                                                                              +
     v_event_id,                                                                                                                                                                                                                                                                               +
     p_interaction_type,                                                                                                                                                                                                                                                                       +
     p_package_id,                                                                                                                                                                                                                                                                             +
     p_metadata,                                                                                                                                                                                                                                                                               +
     p_ip_address,                                                                                                                                                                                                                                                                             +
     p_user_agent                                                                                                                                                                                                                                                                              +
   )                                                                                                                                                                                                                                                                                           +
   RETURNING id INTO v_interaction_id;                                                                                                                                                                                                                                                         +
                                                                                                                                                                                                                                                                                               +
   RETURN v_interaction_id;                                                                                                                                                                                                                                                                    +
 END;                                                                                                                                                                                                                                                                                          +
 $function$                                                                                                                                                                                                                                                                                    +
 
(1 row)

